# Generated by Django 6.0 on 2026-04-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_analytics', 'Can view analytics dashboards')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
