# Generated by Django 6.0.2 on 2026-03-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SquireTrialThread",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTV", "Active"),
                            ("SUCC", "Succeeded"),
                            ("DENY", "Denied"),
                        ],
                        db_index=True,
                        default="ACTV",
                        max_length=4,
                    ),
                ),
                (
                    "thread_id",
                    models.BigIntegerField(
                        help_text="Discord Thread ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "squire_id",
                    models.BigIntegerField(
                        help_text="Discord User ID of the subject squire"
                    ),
                ),
                (
                    "initiator_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discord User ID of the initiator",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "permissions": [
                    ("can_mod_squiretrialthread", "Can start/conclude a Squire Trial"),
                    (
                        "can_feedback_squiretrialthread",
                        "Can give feedback on Squire Trial",
                    ),
                ],
            },
        ),
    ]
