# Generated by Django 6.0 on 2026-03-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0003_merged_initial_setup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmembershipapplicationrecord',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical membership application record',
                'verbose_name_plural': 'historical membership application records',
            },
        ),
        migrations.AlterModelOptions(
            name='historicalrsiverification',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical rsi verification',
                'verbose_name_plural': 'historical rsi verifications',
            },
        ),
    ]