# Generated by Django 6.0 on 2026-03-27 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('candidacy', '0004_alter_historicalmembershipapplicationrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmembershipapplicationrecord',
            name='history_user_id',
        ),
        migrations.RemoveField(
            model_name='historicalrsiverification',
            name='history_user_id',
        ),
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='age_warning',
            field=models.BooleanField(default=False, help_text='True if applicant age < min_age'),
        ),
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='applicant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='membership_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidacy.membershipapplicationtype'),
        ),
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='thread_archived',
            field=models.BooleanField(default=False, help_text='Whether the thread has been auto-archived.'),
        ),
        migrations.AddField(
            model_name='historicalrsiverification',
            name='enlisted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrsiverification',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrsiverification',
            name='org_membership',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplicationrecord',
            name='age_warning',
            field=models.BooleanField(default=False, help_text='True if applicant age < min_age'),
        ),
        migrations.AddField(
            model_name='membershipapplicationrecord',
            name='thread_archived',
            field=models.BooleanField(default=False, help_text='Whether the thread has been auto-archived.'),
        ),
        migrations.AddField(
            model_name='rsiverification',
            name='enlisted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsiverification',
            name='org_membership',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Description and requirements'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this is currently active'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='kind',
            field=models.CharField(choices=[('STAFF', 'Staff Position'), ('TRNG', 'Training Program')], db_index=True, help_text='Is this a staff or training application?', max_length=10),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='name',
            field=models.CharField(help_text='Name of the program/position', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='on_accept_disclaimer',
            field=models.TextField(blank=True, help_text='Text to give to a user when they are accepted.'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='on_accept_gives_permission_groups',
            field=models.ManyToManyField(help_text='When accepted automatically give these permission groups to the user.', related_name='given_by_application_type', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='question_1',
            field=models.CharField(blank=True, help_text='Question 1 (Optional, if all questions are empty skips modal)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='question_2',
            field=models.CharField(blank=True, help_text='Question 2 (Optional)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='question_3',
            field=models.CharField(blank=True, help_text='Question 3 (Optional)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='question_4',
            field=models.CharField(blank=True, help_text='Question 4 (Optional)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='question_5',
            field=models.CharField(blank=True, help_text='Question 5 (Optional)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmembershipapplicationrecord',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalmembershipapplicationrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmembershipapplicationrecord',
            name='thread_id',
            field=models.BigIntegerField(db_index=True, help_text='Discord Thread Snowflake. Thread is locked/archived on close, never deleted.'),
        ),
        migrations.AlterField(
            model_name='historicalrsiverification',
            name='discord_id',
            field=models.BigIntegerField(db_index=True, help_text='Discord User Snowflake'),
        ),
        migrations.AlterField(
            model_name='historicalrsiverification',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalrsiverification',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='membershipapplicationrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membershipapplicationrecord',
            name='thread_id',
            field=models.BigIntegerField(help_text='Discord Thread Snowflake. Thread is locked/archived on close, never deleted.', unique=True),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown in the portal embed field'),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive types are hidden from the portal'),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='name',
            field=models.CharField(help_text="Display name shown in Discord (e.g. 'Legion', 'Auxiliary')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='on_accept_disclaimer',
            field=models.TextField(blank=True, default='## ✅ Application Approved\n\nWelcome, {applicant}!\n\nYou are now a **{rank_prefix} {rank_name}**.\n\nHead to {discipline_channel} and choose your discipline(s).\n\n*This thread will be archived in {archive_hours} hours.*', help_text='Message posted to the application thread on approval. Supports: {applicant} {rank_prefix} {rank_name} {discipline_channel}'),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='on_accept_gives_permission_groups',
            field=models.ManyToManyField(blank=True, help_text='Permission groups automatically added to the user on approval.', related_name='given_by_membership_type', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='on_accept_trial_rank_pk',
            field=models.PositiveIntegerField(blank=True, help_text='PK of the OrgRank granted to the applicant on approval (trial rank). Find the PK on the OrgRank list in Django admin. Leave blank to skip rank assignment.', null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='question_1',
            field=models.CharField(blank=True, help_text='Question 1 (if all blank, modal is skipped)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='question_2',
            field=models.CharField(blank=True, help_text='Question 2 (Optional)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='question_3',
            field=models.CharField(blank=True, help_text='Question 3 (Optional)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='question_4',
            field=models.CharField(blank=True, help_text='Question 4 (Optional)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='question_5',
            field=models.CharField(blank=True, help_text='Question 5 (Optional)', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='welcome_message',
            field=models.CharField(blank=True, default='{applicant}, welcome as **{rank_prefix} {rank_name}**!', help_text='Short ping posted to the welcome channel on approval. Supports: {applicant} {rank_prefix} {rank_name}', max_length=400),
        ),
        migrations.AlterField(
            model_name='rsiverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
