# Generated by Django 6.0.3 on 2026-03-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "candidacy",
            "0005_remove_historicalmembershipapplicationrecord_history_user_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignableDiscipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description shown in the Discord selection menu.",
                    ),
                ),
                (
                    "notification_channel_id",
                    models.BigIntegerField(
                        default=0,
                        help_text="Discord Channel ID where a message is sent when a user joins.",
                    ),
                ),
                (
                    "notification_message",
                    models.TextField(
                        blank=True,
                        default="{user} has joined the **{discipline}** discipline!",
                        help_text="Message sent to the notification channel. Supports: {user} (mention), {name} (display name), {discipline} (discipline name).",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "permission_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The Django permission groups to grant upon selection.",
                        related_name="assignable_disciplines",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_self_assign_discipline", "Can assign this discipline to self")
                ],
            },
        ),
    ]
