# Generated by Django 6.0 on 2026-04-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0008_membershipapplicationtype_explicit_m2m_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplicationtypegroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
