# Generated by Django 6.0 on 2026-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0013_fix_rsiverification_legacy_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_text', models.TextField(blank=True, default='', help_text="Full rules text. Separate pages with a line containing only '---' (triple-dash). Applicants must click through every page before the agree button appears.")),
            ],
            options={
                'verbose_name': 'Membership Rules',
                'verbose_name_plural': 'Membership Rules',
            },
        ),
    ]
