# Generated by Django 6.0 on 2026-04-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0015_drop_verification_data_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplicationtype',
            name='age_question_index',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None — no age check'), (1, 'Question 1'), (2, 'Question 2'), (3, 'Question 3'), (4, 'Question 4'), (5, 'Question 5')], default=0, help_text="Which question asks for the applicant's age? That answer will be validated as a whole number and compared against the minimum age preference. Set to 'None' to disable age checking for this application type."),
        ),
    ]
