# Generated by Django 6.0 on 2026-04-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0016_add_age_question_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(db_index=True, unique=True)),
                ('rules_hash', models.CharField(max_length=64)),
                ('agreed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rules Agreement',
                'verbose_name_plural': 'Rules Agreements',
            },
        ),
    ]
