# Generated by Django 6.0 on 2026-04-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0019_promote_rank_and_promotion_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmembershipapplicationrecord',
            name='promoted_by_id',
        ),
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='promoted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
