# Generated by Django 6.0 on 2026-04-20 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('candidacy', '0020_remove_historicalmembershipapplicationrecord_promoted_by_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='primary_focus',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Primary focus (discipline) confirmed by the approving reviewer at approval time.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidacy.assignablediscipline'),
        ),
        migrations.AddField(
            model_name='membershipapplicationrecord',
            name='primary_focus',
            field=models.ForeignKey(blank=True, help_text='Primary focus (discipline) confirmed by the approving reviewer at approval time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_focus_records', to='candidacy.assignablediscipline'),
        ),
        migrations.AddField(
            model_name='membershipapplicationtype',
            name='on_promote_trial_rank_pk',
            field=models.PositiveIntegerField(blank=True, help_text='PK of the OrgRank assigned by the **Trial** option on the Promote button (intermediate / probationary rank). Leave blank to omit the Trial option.', null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplicationtype',
            name='on_promote_rank_pk',
            field=models.PositiveIntegerField(blank=True, help_text='PK of the OrgRank assigned by the **Legion** option on the Promote button (full member rank). Leave blank to omit the Legion option.', null=True),
        ),
        migrations.CreateModel(
            name='MembershipApplicationTypeEvalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('membershipapplicationtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidacy.membershipapplicationtype')),
            ],
            options={
                'db_table': 'candidacy_membershiptype_evalgroups',
                'unique_together': {('membershipapplicationtype', 'group')},
            },
        ),
        migrations.AddField(
            model_name='membershipapplicationtype',
            name='evaluation_permission_groups',
            field=models.ManyToManyField(blank=True, help_text="Groups shown in the 'Grant Evaluation' review button's selector (e.g. Blue Channel access for evaluating the applicant).", related_name='eval_granted_by_membership_type', through='candidacy.MembershipApplicationTypeEvalGroup', to='auth.group'),
        ),
    ]
