# Generated by Django 6.0 on 2026-04-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0021_historicalmembershipapplicationrecord_primary_focus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipEmbedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('ACCEPT', 'On Acceptance'), ('PROMOTE_TRIAL', 'On Promote → Trial'), ('PROMOTE_LEGION', 'On Promote → Legion')], db_index=True, max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, help_text='Optional text message posted above the embed. Supports placeholders and mentions.')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, help_text='Main embed body. Supports placeholders.')),
                ('color_hex', models.CharField(blank=True, default='#5865F2', help_text='Hex color like #5865F2. Leave blank for Discord blurple.', max_length=7)),
                ('image_url', models.URLField(blank=True, help_text='Large image at the bottom of the embed.', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Small image on the top right.', max_length=500)),
                ('include_welcome_card', models.BooleanField(default=False, help_text='Generate and attach the server welcome card (overrides image_url).')),
                ('author_name', models.CharField(blank=True, max_length=256)),
                ('author_icon_url', models.URLField(blank=True, max_length=500)),
                ('footer_text', models.CharField(blank=True, max_length=2048)),
                ('footer_icon_url', models.URLField(blank=True, max_length=500)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_messages', to='candidacy.membershipapplicationtype')),
            ],
            options={
                'verbose_name': 'Membership Embed Message',
                'verbose_name_plural': 'Membership Embed Messages',
                'unique_together': {('membership_type', 'event')},
            },
        ),
    ]
