# Generated by Django 6.0 on 2026-04-23 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0022_membershipembedmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingLeaderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, help_text='ISO week Monday date')),
                ('posted_message_id', models.BigIntegerField(blank=True, help_text='Discord message ID of the posted assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leaders', models.ManyToManyField(blank=True, related_name='onboarding_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'permissions': [('manage_onboarding_assignments', 'Can manage onboarding leader assignments')],
            },
        ),
    ]
