# Generated by Django 6.0 on 2026-04-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0023_onboardingleaderassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='flag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='flagged_suspicious',
            field=models.BooleanField(default=False, help_text='Flagged by staff as a suspicious applicant.'),
        ),
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='follow_up_sent',
            field=models.BooleanField(default=False, help_text='Whether the post-approval follow-up DM has been sent.'),
        ),
        migrations.AddField(
            model_name='membershipapplicationrecord',
            name='flag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='membershipapplicationrecord',
            name='flagged_suspicious',
            field=models.BooleanField(default=False, help_text='Flagged by staff as a suspicious applicant.'),
        ),
        migrations.AddField(
            model_name='membershipapplicationrecord',
            name='follow_up_sent',
            field=models.BooleanField(default=False, help_text='Whether the post-approval follow-up DM has been sent.'),
        ),
    ]
