# Generated by Django 6.0 on 2026-04-23 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0024_historicalmembershipapplicationrecord_flag_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='referral_note',
            field=models.CharField(blank=True, default='', help_text="Free-text note about how the applicant found us (e.g. 'Reddit post', 'Friend of [name]').", max_length=200),
        ),
        migrations.AddField(
            model_name='historicalmembershipapplicationrecord',
            name='referred_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Org member who referred / recruited this applicant.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplicationrecord',
            name='referral_note',
            field=models.CharField(blank=True, default='', help_text="Free-text note about how the applicant found us (e.g. 'Reddit post', 'Friend of [name]').", max_length=200),
        ),
        migrations.AddField(
            model_name='membershipapplicationrecord',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Org member who referred / recruited this applicant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
