# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0026_remove_applicationtype_orphaned_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationrecord',
            options={'default_permissions': (), 'ordering': ['-submitted_at'], 'permissions': [('can_review_application', 'Can review applications'), ('can_submit_application', 'Can submit applications')]},
        ),
        migrations.AlterModelOptions(
            name='assignablediscipline',
            options={'default_permissions': (), 'permissions': [('can_self_assign_discipline', 'Can assign this discipline to self')]},
        ),
        migrations.AlterModelOptions(
            name='membershipapplicationrecord',
            options={'default_permissions': (), 'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='membershipapplicationtype',
            options={'default_permissions': (), 'permissions': [('can_review_membershipapplication', 'Can review membership applications')]},
        ),
        migrations.AlterModelOptions(
            name='membershipapplicationtypeevalgroup',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='membershipapplicationtypegroup',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='membershipembedmessage',
            options={'default_permissions': (), 'verbose_name': 'Membership Embed Message', 'verbose_name_plural': 'Membership Embed Messages'},
        ),
        migrations.AlterModelOptions(
            name='membershiprules',
            options={'default_permissions': (), 'verbose_name': 'Membership Rules', 'verbose_name_plural': 'Membership Rules'},
        ),
        migrations.AlterModelOptions(
            name='onboardingleaderassignment',
            options={'default_permissions': (), 'ordering': ['-week_start'], 'permissions': [('manage_onboarding_assignments', 'Can manage onboarding leader assignments')]},
        ),
        migrations.AlterModelOptions(
            name='rsiverification',
            options={'default_permissions': (), 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rulesagreement',
            options={'default_permissions': (), 'verbose_name': 'Rules Agreement', 'verbose_name_plural': 'Rules Agreements'},
        ),
        migrations.AlterModelOptions(
            name='squiretrialthread',
            options={'default_permissions': (), 'ordering': ['-started_at'], 'permissions': [('can_mod_squiretrialthread', 'Can start/conclude a Squire Trial'), ('can_feedback_squiretrialthread', 'Can give feedback on Squire Trial')]},
        ),
    ]
