# Generated by Django 6.0 on 2026-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSIStatusSnapshot',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('raw_json', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSI Status Snapshot',
                'db_table': 'sc_tracker_rsi_snapshot',
            },
        ),
        migrations.CreateModel(
            name='StatusChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(db_index=True, unique=True)),
                ('message_id', models.BigIntegerField()),
                ('message_type', models.CharField(default='status_embed', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status Channel Message',
                'db_table': 'sc_tracker_status_channel_message',
            },
        ),
        migrations.CreateModel(
            name='StatusSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status Subscription',
                'verbose_name_plural': 'Status Subscriptions',
                'db_table': 'sc_tracker_status_subscription',
                'permissions': [('can_subscribe_status', 'Can subscribe to RSI status DM alerts')],
            },
        ),
        migrations.CreateModel(
            name='HangarStatusMessage',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('last_phase_change', models.DateTimeField(blank=True, null=True)),
                ('last_light_change', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.IntegerField(default=0)),
                ('last_website_sync', models.DateTimeField(blank=True, null=True)),
                ('website_sync_attempts', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hangar Status Message',
                'db_table': 'sc_tracker_hangar_status_message',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_hangar_status_record')],
            },
        ),
        migrations.CreateModel(
            name='RSIIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=255, unique=True)),
                ('discord_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.TextField()),
                ('affected', models.JSONField(default=list)),
                ('severity', models.CharField(max_length=50)),
                ('permalink', models.TextField()),
                ('kind', models.CharField(max_length=50)),
                ('markdown_content', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('informational', models.BooleanField(default=False)),
                ('rsi_created_at', models.DateTimeField(blank=True, null=True)),
                ('rsi_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rsi_lastmod_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSI Issue',
                'verbose_name_plural': 'RSI Issues',
                'db_table': 'sc_tracker_rsi_issue',
                'indexes': [models.Index(fields=['resolved', 'updated_at'], name='sc_tracker__resolve_fa9759_idx'), models.Index(fields=['severity'], name='sc_tracker__severit_27055f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusDMMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.BigIntegerField(db_index=True)),
                ('dm_message_id', models.BigIntegerField()),
                ('incident_guid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('incident_title', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('confirmation', 'Confirmation'), ('update', 'Incident Update'), ('unsubscribe', 'Unsubscribe'), ('test', 'Test')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Status DM Message',
                'verbose_name_plural': 'Status DM Messages',
                'db_table': 'sc_tracker_status_dm_message',
                'indexes': [models.Index(fields=['discord_user_id', 'message_type'], name='sc_tracker__discord_418ea7_idx'), models.Index(fields=['incident_guid', 'created_at'], name='sc_tracker__inciden_8e7a78_idx')],
            },
        ),
    ]
