# Generated by Django 6.0 on 2026-03-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCTrackerConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('hangar_channel_id', models.BigIntegerField(default=0, help_text='Discord channel ID where the Executive Hangar timer embed is posted.')),
                ('status_channel_id', models.BigIntegerField(default=0, help_text='Discord channel ID where the RSI Status embed is posted.')),
                ('hangar_phase_role_id', models.BigIntegerField(default=0, help_text='Role pinged on GREEN ↔ RED phase transitions. 0 = no ping.')),
                ('hangar_light_role_id', models.BigIntegerField(default=0, help_text='Role pinged on significant light changes. 0 = no ping.')),
                ('hangar_open_ms', models.BigIntegerField(default=3900338, help_text='OPEN_DURATION in ms from exec.xyxyll.com/app.js')),
                ('hangar_close_ms', models.BigIntegerField(default=7200623, help_text='CLOSE_DURATION in ms from exec.xyxyll.com/app.js')),
                ('hangar_t0_ms', models.BigIntegerField(default=1738447794775, help_text='INITIAL_OPEN_TIME as Unix ms from exec.xyxyll.com/app.js. Update after every SC patch.')),
                ('hangar_patch_info', models.CharField(default='Updated Feb 14, 2026 for Star Citizen Patch 4.6.0-LIVE (Server Version 11218823)', help_text='Human-readable patch label shown in embeds.', max_length=255)),
                ('hangar_enabled', models.BooleanField(default=True)),
                ('status_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SC Tracker Configuration',
                'verbose_name_plural': 'SC Tracker Configuration',
                'db_table': 'sc_tracker_config',
            },
        ),
        migrations.RemoveConstraint(
            model_name='hangarstatusmessage',
            name='single_hangar_status_record',
        ),
        migrations.AddConstraint(
            model_name='hangarstatusmessage',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='sc_tracker_single_hangar_status_record'),
        ),
        migrations.AddConstraint(
            model_name='sctrackerconfig',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='sc_tracker_single_config_record'),
        ),
    ]
