# Generated by Django 6.0 on 2026-04-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_tracker', '0003_populate_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sctrackerconfig',
            name='hangar_patch_info',
            field=models.CharField(default='Updated Mar 27, 2026 for Star Citizen Patch 4.7.0-LIVE (Server Version 11518367)', help_text='Human-readable patch label shown in embeds.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sctrackerconfig',
            name='hangar_t0_ms',
            field=models.BigIntegerField(default=1774501916500, help_text='INITIAL_OPEN_TIME as Unix ms from exec.xyxyll.com/app.js. Update after every SC patch.'),
        ),
    ]
