# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc_tracker', '0005_hangarstatusmessage_phase_notification_message_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hangarstatusmessage',
            options={'default_permissions': (), 'verbose_name': 'Hangar Status Message'},
        ),
        migrations.AlterModelOptions(
            name='rsiissue',
            options={'default_permissions': (), 'verbose_name': 'RSI Issue', 'verbose_name_plural': 'RSI Issues'},
        ),
        migrations.AlterModelOptions(
            name='rsistatussnapshot',
            options={'default_permissions': (), 'verbose_name': 'RSI Status Snapshot'},
        ),
        migrations.AlterModelOptions(
            name='sctrackerconfig',
            options={'default_permissions': (), 'verbose_name': 'SC Tracker Configuration', 'verbose_name_plural': 'SC Tracker Configuration'},
        ),
        migrations.AlterModelOptions(
            name='statuschannelmessage',
            options={'default_permissions': (), 'verbose_name': 'Status Channel Message'},
        ),
        migrations.AlterModelOptions(
            name='statusdmmessage',
            options={'default_permissions': (), 'verbose_name': 'Status DM Message', 'verbose_name_plural': 'Status DM Messages'},
        ),
        migrations.AlterModelOptions(
            name='statussubscription',
            options={'default_permissions': (), 'permissions': [('can_subscribe_status', 'Can subscribe to RSI status DM alerts')], 'verbose_name': 'Status Subscription', 'verbose_name_plural': 'Status Subscriptions'},
        ),
    ]
