# Generated by Django 6.0.2 on 2026-03-20 05:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discordauth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoggedDiscordChannel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="Discord Channel ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("channel_type", models.CharField(db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoggedVoiceStateSnapshot",
            fields=[
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, primary_key=True, serialize=False
                    ),
                ),
                ("expected_resolution", models.DurationField()),
                ("compiled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserVoiceProfile",
            fields=[],
            options={
                "verbose_name": "User Voice History",
                "verbose_name_plural": "User Voice Histories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("discordauth.discorduser",),
        ),
        migrations.CreateModel(
            name="HistoricalLoggedDiscordChannel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_index=True, help_text="Discord Channel ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("channel_type", models.CharField(db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical logged discord channel",
                "verbose_name_plural": "historical logged discord channels",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLoggedDiscordMessage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_index=True, help_text="Discord Message ID"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("NEW", "New"), ("CNG", "Edit"), ("DEL", "Delete")],
                        db_index=True,
                        default="NEW",
                        max_length=3,
                    ),
                ),
                (
                    "moderated",
                    models.CharField(
                        choices=[("NO", "No"), ("YES", "Yes"), ("UNK", "Unsure")],
                        db_index=True,
                        default="UNK",
                        max_length=3,
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="discordauth.discorduser",
                    ),
                ),
                (
                    "discord_executor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Not Known/Logged when a mod deletes attachments, only mostly reliable on mod msg deletes (Discord Limits)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="discordauth.discorduser",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="discordlogger.loggeddiscordchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical logged discord message",
                "verbose_name_plural": "historical logged discord messages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LoggedDiscordMessage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="Discord Message ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("NEW", "New"), ("CNG", "Edit"), ("DEL", "Delete")],
                        db_index=True,
                        default="NEW",
                        max_length=3,
                    ),
                ),
                (
                    "moderated",
                    models.CharField(
                        choices=[("NO", "No"), ("YES", "Yes"), ("UNK", "Unsure")],
                        db_index=True,
                        default="UNK",
                        max_length=3,
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author_for_discord_message",
                        to="discordauth.discorduser",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discordlogger.loggeddiscordchannel",
                    ),
                ),
                (
                    "discord_executor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Not Known/Logged when a mod deletes attachments, only mostly reliable on mod msg deletes (Discord Limits)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executor_for_discord_message",
                        to="discordauth.discorduser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompiledLoggedVoiceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval_start_at", models.DateTimeField(db_index=True)),
                ("interval_stop_at", models.DateTimeField(db_index=True)),
                ("self_mute", models.BooleanField(default=False)),
                ("self_deaf", models.BooleanField(default=False)),
                ("server_mute", models.BooleanField(default=False)),
                ("server_deaf", models.BooleanField(default=False)),
                ("self_stream", models.BooleanField(default=False)),
                ("self_video", models.BooleanField(default=False)),
                (
                    "discorduser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compiled_voice_state",
                        to="discordauth.discorduser",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compiled_voice_state",
                        to="discordlogger.loggeddiscordchannel",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["discorduser", "interval_start_at", "interval_stop_at"],
                        name="discordlogg_discord_3fcbd0_idx",
                    ),
                    models.Index(
                        fields=["interval_start_at", "interval_stop_at"],
                        name="discordlogg_interva_7d8dc8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoggedVoiceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discorduid", models.PositiveBigIntegerField()),
                ("self_mute", models.BooleanField(default=False)),
                ("self_deaf", models.BooleanField(default=False)),
                ("server_mute", models.BooleanField(default=False)),
                ("server_deaf", models.BooleanField(default=False)),
                ("self_stream", models.BooleanField(default=False)),
                ("self_video", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discordlogger.loggeddiscordchannel",
                    ),
                ),
                (
                    "for_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discordlogger.loggedvoicestatesnapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["discorduid", "for_snapshot"],
                        name="discordlogg_discord_ad4042_idx",
                    )
                ],
            },
        ),
    ]
