# Generated by Django 6.0.2 on 2026-03-20 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordauth", "0001_initial"),
        ("discordlogger", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="loggedvoicestate",
            name="discordlogg_discord_ad4042_idx",
        ),
        migrations.AddField(
            model_name="loggedvoicestate",
            name="discorduser",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="discordauth.discorduser",
            ),
        ),
        migrations.AlterField(
            model_name="compiledloggedvoicestate",
            name="channel",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="compiled_voice_state",
                to="discordlogger.loggeddiscordchannel",
            ),
        ),
        migrations.AlterField(
            model_name="compiledloggedvoicestate",
            name="discorduser",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="compiled_voice_state",
                to="discordauth.discorduser",
            ),
        ),
        migrations.AlterField(
            model_name="loggeddiscordmessage",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="author_for_discord_message",
                to="discordauth.discorduser",
            ),
        ),
        migrations.AlterField(
            model_name="loggeddiscordmessage",
            name="discord_executor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Not Known/Logged when a mod deletes attachments, only mostly reliable on mod msg deletes (Discord Limits)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="executor_for_discord_message",
                to="discordauth.discorduser",
            ),
        ),
        migrations.AlterField(
            model_name="loggedvoicestate",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="discordlogger.loggeddiscordchannel",
            ),
        ),
        migrations.AddIndex(
            model_name="loggedvoicestate",
            index=models.Index(
                fields=["discorduser", "for_snapshot"],
                name="discordlogg_discord_f0f13d_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="loggedvoicestate",
            name="discorduid",
        ),
    ]
