# Generated by Django 6.0.2 on 2026-03-20 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "discordlogger",
            "0002_remove_loggedvoicestate_discordlogg_discord_ad4042_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loggeddiscordchannel",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="historicalloggeddiscordchannel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="discordlogger.loggeddiscordchannel",
            ),
        ),
        migrations.AddField(
            model_name="historicalloggeddiscordchannel",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loggeddiscordchannel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children",
                to="discordlogger.loggeddiscordchannel",
            ),
        ),
        migrations.AddField(
            model_name="loggeddiscordchannel",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
