# Generated by Django 6.0.3 on 2026-03-31 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordlogger", "0003_alter_loggeddiscordchannel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggeddiscordmessage",
            name="channel",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="logged_messages",
                to="discordlogger.loggeddiscordchannel",
            ),
        ),
    ]
