# Generated by Django 6.0 on 2026-04-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogger', '0004_alter_loggeddiscordmessage_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loggeddiscordmessage',
            options={'permissions': [('view_transcripts', 'Can export channel message transcripts')]},
        ),
    ]
