# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogger', '0005_alter_loggeddiscordmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compiledloggedvoicestate',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='loggeddiscordchannel',
            options={'default_permissions': (), 'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='loggeddiscordmessage',
            options={'default_permissions': (), 'permissions': [('view_transcripts', 'Can export channel message transcripts')]},
        ),
        migrations.AlterModelOptions(
            name='loggedvoicestate',
            options={'default_permissions': ()},
        ),
    ]
