# Generated by Django 6.0.5 on 2026-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogger', '0006_alter_compiledloggedvoicestate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exporter_discord_id', models.BigIntegerField(db_index=True, help_text='Discord user ID of the staff member who ran /transcript')),
                ('channel_id', models.BigIntegerField(db_index=True, help_text='Discord channel ID that was exported')),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('exported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Transcript Export Log',
                'verbose_name_plural': 'Transcript Export Logs',
                'ordering': ['-exported_at'],
                'default_permissions': (),
            },
        ),
    ]
