# Generated by Django 6.0.2 on 2026-02-20 13:56

import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unifieduser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorgplayer",
            name="id",
            field=django_ulid.models.ULIDField(
                db_index=True, default=ulid.api.api.Api.new, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="orgplayer",
            name="id",
            field=django_ulid.models.ULIDField(
                default=ulid.api.api.Api.new,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
