# Generated by Django 6.0.2 on 2026-02-26 20:56

import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("unifieduser", "0002_alter_historicalorgplayer_id_alter_orgplayer_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="orgplayer",
            managers=[],
        ),
        migrations.AlterField(
            model_name="historicalorgplayer",
            name="id",
            field=django_ulid.models.ULIDField(
                db_index=True, default=ulid.api.api.Api.new, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="orgplayer",
            name="id",
            field=django_ulid.models.ULIDField(
                default=ulid.api.api.Api.new,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="OrgRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Visual prefix for the user (e.g. '[LM]')",
                        max_length=7,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Django auth groups synced to users with this rank.",
                        related_name="ranks",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="historicalorgplayer",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="unifieduser.orgrank",
            ),
        ),
        migrations.AddField(
            model_name="orgplayer",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="unifieduser.orgrank",
            ),
        ),
    ]
