# Generated by Django 6.0.2 on 2026-03-04 00:08

import app.unifieduser.models
import django_ulid.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unifieduser", "0003_alter_orgplayer_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="orgplayer",
            managers=[
                ("objects", app.unifieduser.models.OrgPlayerManager()),
            ],
        ),
        migrations.AlterField(
            model_name="historicalorgplayer",
            name="id",
            field=django_ulid.models.ULIDField(
                db_index=True, default=app.unifieduser.models.ulid_new, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="orgplayer",
            name="id",
            field=django_ulid.models.ULIDField(
                default=app.unifieduser.models.ulid_new,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
