# Generated by Django 6.0 on 2026-04-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifieduser', '0004_alter_orgplayer_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorgplayer',
            name='first_event_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the member's first recorded event attendance. Set automatically.", null=True),
        ),
        migrations.AddField(
            model_name='historicalorgplayer',
            name='timezone_str',
            field=models.CharField(blank=True, default='', help_text="IANA timezone string, e.g. 'America/New_York'. Set by the member via /set_timezone.", max_length=64),
        ),
        migrations.AddField(
            model_name='orgplayer',
            name='first_event_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the member's first recorded event attendance. Set automatically.", null=True),
        ),
        migrations.AddField(
            model_name='orgplayer',
            name='timezone_str',
            field=models.CharField(blank=True, default='', help_text="IANA timezone string, e.g. 'America/New_York'. Set by the member via /set_timezone.", max_length=64),
        ),
    ]
