# Generated by Django 6.0 on 2026-04-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifieduser', '0005_historicalorgplayer_first_event_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorgplayer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical org player', 'verbose_name_plural': 'historical org players'},
        ),
        migrations.AlterModelOptions(
            name='orgplayer',
            options={'permissions': [('view_org_roster', 'Can view the org member roster')]},
        ),
    ]
