# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifieduser', '0006_alter_historicalorgplayer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaynamesearchcache',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='orgplayer',
            options={'default_permissions': (), 'permissions': [('view_org_roster', 'Can view the org member roster')]},
        ),
    ]
