# Generated by Django 6.0 on 2026-04-23 17:45

import app.main.util.db
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('WARN', 'Warning'), ('MUTE', 'Mute / Silence'), ('KICK', 'Kick'), ('BAN', 'Ban'), ('BLACKLIST', 'Blacklist'), ('INACTIVE', 'Mark Inactive'), ('REPRIMAND', 'Formal Reprimand'), ('NOTE', 'Staff Note'), ('FORCEROL', 'Force Role Change')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARDONED', 'Pardoned / Lifted'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=10)),
                ('reason', models.TextField()),
                ('internal_notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, action auto-lifts at this time.', null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('forced_rank_id', models.PositiveIntegerField(blank=True, help_text='OrgRank PK set via force role change.', null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pardoned_at', models.DateTimeField(blank=True, null=True)),
                ('discord_thread_id', models.BigIntegerField(blank=True, help_text='Discord thread ID for this action, if created.', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_approvals', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_issued', to=settings.AUTH_USER_MODEL)),
                ('pardoned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_pardons', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'permissions': [('can_issue_warn', 'Can issue warnings'), ('can_issue_mute', 'Can mute/silence members'), ('can_issue_kick', 'Can kick members'), ('can_issue_ban', 'Can ban members'), ('can_issue_blacklist', 'Can blacklist members'), ('can_mark_inactive', 'Can mark members inactive'), ('can_issue_reprimand', 'Can issue formal reprimands'), ('can_add_staff_note', 'Can add staff notes to members'), ('can_force_role_change', 'Can force a rank/role change'), ('can_approve_discipline', 'Can approve pending disciplinary actions'), ('can_view_records', 'Can view disciplinary records')],
            },
            bases=(app.main.util.db.DBAwareModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('DEMOTION', 'Demotion'), ('ROLE_ASSIGN', 'Role Assignment'), ('ROLE_REMOVE', 'Role Removal'), ('DISCIPLINE', 'Disciplinary Action'), ('ONBOARD', 'Onboarding Decision'), ('STAFF', 'Staff Action / Note'), ('NOMINATION', 'Nomination Awarded')], db_index=True, max_length=20)),
                ('summary', models.CharField(max_length=500)),
                ('detail', models.TextField(blank=True)),
                ('rank_before_id', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_after_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_log_actor', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_log_subject', to=settings.AUTH_USER_MODEL)),
                ('disciplinary_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='leadership.disciplinaryrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_view_decision_log', 'Can view decision log')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDisciplinaryRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('WARN', 'Warning'), ('MUTE', 'Mute / Silence'), ('KICK', 'Kick'), ('BAN', 'Ban'), ('BLACKLIST', 'Blacklist'), ('INACTIVE', 'Mark Inactive'), ('REPRIMAND', 'Formal Reprimand'), ('NOTE', 'Staff Note'), ('FORCEROL', 'Force Role Change')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARDONED', 'Pardoned / Lifted'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=10)),
                ('reason', models.TextField()),
                ('internal_notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, action auto-lifts at this time.', null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('forced_rank_id', models.PositiveIntegerField(blank=True, help_text='OrgRank PK set via force role change.', null=True)),
                ('issued_at', models.DateTimeField(blank=True, editable=False)),
                ('pardoned_at', models.DateTimeField(blank=True, null=True)),
                ('discord_thread_id', models.BigIntegerField(blank=True, help_text='Discord thread ID for this action, if created.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pardoned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical disciplinary record',
                'verbose_name_plural': 'historical disciplinary records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='disciplinaryrecord',
            index=models.Index(fields=['subject', 'action_type', 'status'], name='leadership__subject_6297b0_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinaryrecord',
            index=models.Index(fields=['issued_at'], name='leadership__issued__bd32e0_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['subject', 'event_type'], name='leadership__subject_0da50f_idx'),
        ),
    ]
