# Generated by Django 6.0 on 2026-04-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinaryrecord',
            options={'ordering': ['-issued_at'], 'permissions': [('can_issue_warn', 'Can issue warnings'), ('can_issue_mute', 'Can mute/silence members'), ('can_issue_kick', 'Can kick members'), ('can_issue_ban', 'Can ban members'), ('can_issue_blacklist', 'Can blacklist members'), ('can_mark_inactive', 'Can mark members inactive'), ('can_issue_reprimand', 'Can issue formal reprimands'), ('can_add_staff_note', 'Can add staff notes to members'), ('can_force_role_change', 'Can force a rank/role change'), ('can_approve_discipline', 'Can approve pending disciplinary actions'), ('can_view_records', 'Can view disciplinary records'), ('can_promote', 'Can promote members to a higher rank'), ('can_demote', 'Can demote members to a lower rank')]},
        ),
    ]
