# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_alter_disciplinaryrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decisionlog',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('can_view_decision_log', 'Can view decision log')]},
        ),
        migrations.AlterModelOptions(
            name='disciplinaryrecord',
            options={'default_permissions': (), 'ordering': ['-issued_at'], 'permissions': [('can_issue_warn', 'Can issue warnings'), ('can_issue_mute', 'Can mute/silence members'), ('can_issue_kick', 'Can kick members'), ('can_issue_ban', 'Can ban members'), ('can_issue_blacklist', 'Can blacklist members'), ('can_mark_inactive', 'Can mark members inactive'), ('can_issue_reprimand', 'Can issue formal reprimands'), ('can_add_staff_note', 'Can add staff notes to members'), ('can_force_role_change', 'Can force a rank/role change'), ('can_approve_discipline', 'Can approve pending disciplinary actions'), ('can_view_records', 'Can view disciplinary records'), ('can_promote', 'Can promote members to a higher rank'), ('can_demote', 'Can demote members to a lower rank')]},
        ),
    ]
