# Generated by Django 6.0 on 2026-04-25 16:48

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendanceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emoji', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'permissions': [('can_create_events_with', 'Can create an event with this attendance option.')],
            },
        ),
        migrations.CreateModel(
            name='EventAvailabilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emoji', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'permissions': [('can_create_events_with', 'Can create an event with this availability option.')],
            },
        ),
        migrations.CreateModel(
            name='EventIndicator',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_format', message='Only uppercase letters and numbers are allowed. No spaces or special characters.', regex='^[A-Z0-9]+$')])),
                ('prefix', models.CharField(blank=True, default='◻️', max_length=16)),
                ('name', models.CharField(default='Public', max_length=200)),
                ('description', models.TextField(blank=True, default=str)),
            ],
            options={
                'permissions': [('can_create_events_with', 'Can create an event of this indicator.')],
            },
        ),
        migrations.CreateModel(
            name='EventPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default=str)),
            ],
            options={
                'permissions': [('can_create_events_with', 'Can create an event of this prefix.')],
            },
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_at', models.DateTimeField(blank=True)),
                ('actual_end_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emoji', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('max_slots', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('limit_to_permission_groups', models.ManyToManyField(related_name='attendance_config_limit', to='auth.group')),
                ('limit_to_with_vetting_permission_groups', models.ManyToManyField(related_name='attendance_config_vetting_limit', to='auth.group')),
                ('option', models.ManyToManyField(related_name='option_for_configs', to='orgevents.eventattendanceoption')),
            ],
        ),
        migrations.CreateModel(
            name='EventAvailabilityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emoji', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('max_slots', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('limit_to_permission_groups', models.ManyToManyField(related_name='availability_config_limit', to='auth.group')),
                ('limit_to_with_vetting_permission_groups', models.ManyToManyField(related_name='availability_config_vetting_limit', to='auth.group')),
                ('option', models.ManyToManyField(related_name='option_for_configs', to='orgevents.eventavailabilityoption')),
            ],
        ),
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('codename_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('attendance_options_select_max', models.PositiveSmallIntegerField(default=1)),
                ('availibility_options_select_max', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(blank=True)),
                ('banner_image', models.FileField(upload_to='uploads/')),
                ('has_discord_event', models.BooleanField(default=True)),
                ('planned_start_at', models.DateTimeField(blank=True)),
                ('planned_duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=7200))),
                ('attendance_options', models.ManyToManyField(related_name='config_for_events', to='orgevents.eventattendanceconfig')),
                ('availibility_options', models.ManyToManyField(related_name='config_for_events', to='orgevents.eventavailabilityconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='orgevents.eventindicator')),
                ('organizers', models.ManyToManyField(related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='orgevents.eventprefix')),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to='orgevents.eventreport')),
            ],
            options={
                'permissions': [('can_modify_delete_created', 'Can modify events where they are the value for created_by.'), ('can_modify_delete_organizer', 'Can modify events where they are added to the list of organizers.')],
            },
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('attendance_options_select_max', models.PositiveSmallIntegerField(default=1)),
                ('availibility_options_select_max', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(blank=True)),
                ('banner_image', models.FileField(upload_to='uploads/')),
                ('has_discord_event', models.BooleanField(default=True)),
                ('planned_start_at', models.DateTimeField(blank=True)),
                ('planned_end_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_options', models.ManyToManyField(related_name='template_config_for_events', to='orgevents.eventattendanceconfig')),
                ('availibility_options', models.ManyToManyField(related_name='template_config_for_events', to='orgevents.eventavailabilityconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_templates', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_events', to='orgevents.eventindicator')),
                ('organizers', models.ManyToManyField(related_name='organized_event_templates', to=settings.AUTH_USER_MODEL)),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_events', to='orgevents.eventprefix')),
            ],
            options={
                'permissions': [('can_create_event_with', 'Can use this template to create events'), ('can_set_custom_name', 'When using template to create event can set a custom name'), ('can_set_custom_duration', 'When using template to create event can set a custom duration'), ('can_set_custom_banner', 'When using template to create event can set a custom banner img'), ('can_set_custom_description', 'When using template to create event can set a custom description')],
            },
        ),
    ]
