# Generated by Django 6.0 on 2026-04-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgevents', '0002_organicevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organicevent',
            name='embed_message_id',
            field=models.BigIntegerField(help_text='Main dashboard message in the parent channel'),
        ),
        migrations.AlterField(
            model_name='organicevent',
            name='event_type',
            field=models.CharField(help_text='e.g. DEATHWATCH, SCPVP', max_length=50),
        ),
        migrations.AlterField(
            model_name='organicevent',
            name='starter_id',
            field=models.BigIntegerField(help_text='Discord User ID of the initiator'),
        ),
        migrations.AlterField(
            model_name='organicevent',
            name='thread_id',
            field=models.BigIntegerField(help_text='Discord Thread ID', primary_key=True, serialize=False),
        ),
    ]
