# Generated by Django 6.0.3 on 2026-03-31 08:33

import app.main.util.db
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTrackedCraftedWeapon",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("weapon_name", models.CharField(max_length=255)),
                ("stats", models.JSONField(default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, editable=False)),
                ("gone_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tracked crafted weapon",
                "verbose_name_plural": "historical tracked crafted weapons",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TrackedCraftedWeapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weapon_name", models.CharField(max_length=255)),
                ("stats", models.JSONField(default=dict)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("gone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "permissions": [
                    ("can_submit_new_weapon", "Can submit new weapon"),
                    ("can_see_weapon_listing", "Can see weapon listing"),
                    ("can_request_held_limited", "Can request weapon held for Knights"),
                    ("can_request_held_orgwide", "Can request weapon held for Org"),
                    ("can_approve_requests", "Can approve weapon requests"),
                    ("can_discord_manage_state", "Can manage weapon state in discord"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackedCraftedRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "for_weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="inventory.trackedcraftedweapon",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTrackedCraftedWeaponState",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("USED", "Actively in Use"),
                            ("HELD_K", "Availible for Knights"),
                            ("HELD_O", "Availible for Org"),
                            ("LOST_CIG", "Lost Other"),
                            ("LOST_COMBAT", "Lost in Combat"),
                            ("EXTERNAL", "Not under Org control"),
                            ("AWAIT_RET", "Awaiting Return"),
                        ],
                        db_index=True,
                        default="EXTERNAL",
                        max_length=14,
                    ),
                ),
                ("purpose", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "current_owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "for_weapon",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.trackedcraftedweapon",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tracked crafted weapon state",
                "verbose_name_plural": "historical tracked crafted weapon states",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TrackedCraftedWeaponState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("USED", "Actively in Use"),
                            ("HELD_K", "Availible for Knights"),
                            ("HELD_O", "Availible for Org"),
                            ("LOST_CIG", "Lost Other"),
                            ("LOST_COMBAT", "Lost in Combat"),
                            ("EXTERNAL", "Not under Org control"),
                            ("AWAIT_RET", "Awaiting Return"),
                        ],
                        db_index=True,
                        default="EXTERNAL",
                        max_length=14,
                    ),
                ),
                ("purpose", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "current_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "for_weapon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="inventory.trackedcraftedweapon",
                    ),
                ),
            ],
            bases=(app.main.util.db.OriginalStateMixin, models.Model),
        ),
    ]
