# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_historicalstockitem_stockitem_historicalstockunit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockassignment',
            options={'default_permissions': (), 'ordering': ['-actioned_at']},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'default_permissions': (), 'ordering': ['category', 'name'], 'permissions': [('manage_stock', 'Can add, edit, and remove stock items and units'), ('assign_stock', 'Can assign stock units to knights'), ('view_stock', 'Can view the stock inventory')]},
        ),
        migrations.AlterModelOptions(
            name='stockunit',
            options={'default_permissions': (), 'ordering': ['item__name', '-added_at']},
        ),
        migrations.AlterModelOptions(
            name='trackedcraftedweapon',
            options={'default_permissions': (), 'ordering': ['-submitted_at'], 'permissions': [('can_submit_new_weapon', 'Can submit new weapon'), ('can_see_weapon_listing', 'Can see weapon listing'), ('can_request_held_limited', 'Can request weapon held for Knights'), ('can_request_held_orgwide', 'Can request weapon held for Org'), ('can_approve_requests', 'Can approve weapon requests'), ('can_discord_manage_state', 'Can manage weapon state in discord')]},
        ),
    ]
