# Generated by Django 6.0 on 2026-04-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disfunction', '0003_welcome_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicechannelprofile',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=50, help_text='Lower = higher priority. Evaluated highest-to-lowest when picking a profile.'),
        ),
        # These indexes already exist in the DB (created by orm_models migrations).
        # SeparateDatabaseAndState updates Django's migration state without re-running the DDL.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='userjoinrecord',
                    index=models.Index(fields=['discord_id', 'is_active'], name='orm_models__discord_02dc2d_idx'),
                ),
                migrations.AddIndex(
                    model_name='userjoinrecord',
                    index=models.Index(fields=['discord_id', 'membership_status'], name='orm_models__discord_8c6311_idx'),
                ),
                migrations.AddIndex(
                    model_name='userjoinrecord',
                    index=models.Index(fields=['joined_at'], name='orm_models__joined__65d917_idx'),
                ),
                migrations.AddIndex(
                    model_name='userjoinrecord',
                    index=models.Index(fields=['left_at'], name='orm_models__left_at_206e2e_idx'),
                ),
                migrations.AddIndex(
                    model_name='userjoinrecord',
                    index=models.Index(fields=['last_seen'], name='orm_models__last_se_b94012_idx'),
                ),
                migrations.AddIndex(
                    model_name='userjoinrecord',
                    index=models.Index(fields=['username'], name='orm_models__usernam_a50c42_idx'),
                ),
                migrations.AddIndex(
                    model_name='userjoinrecord',
                    index=models.Index(fields=['global_name'], name='orm_models__global__aed958_idx'),
                ),
                migrations.AddIndex(
                    model_name='userjoinrecord',
                    index=models.Index(fields=['join_count'], name='orm_models__join_co_63a95f_idx'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterModelTable(
            name='historicalvoiceban',
            table=None,
        ),
    ]
