# Generated by Django 6.0 on 2026-04-06 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('disfunction', '0004_alter_voicechannelprofile_sort_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicechannelprofile',
            name='required_permission',
        ),
        migrations.AddField(
            model_name='voicechannelprofile',
            name='required_group',
            field=models.ForeignKey(blank=True, help_text='Django Group whose linked Discord roles grant access to this profile. Leave blank to allow everyone. Wire Discord roles → this group via Org → Group Discord Roles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vc_profiles', to='auth.group'),
        ),
    ]
