# Generated by Django 6.0 on 2026-04-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disfunction', '0005_remove_voicechannelprofile_required_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicechannelprofile',
            name='required_group',
        ),
        migrations.AddField(
            model_name='voicechannelprofile',
            name='required_discord_role_id',
            field=models.BigIntegerField(blank=True, help_text='Discord Role ID required to use this profile. Leave blank = everyone.', null=True),
        ),
    ]
