# Generated by Django 6.0 on 2026-04-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disfunction', '0006_remove_voicechannelprofile_required_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicechannelprofile',
            name='permissions_source_channel_id',
            field=models.BigIntegerField(blank=True, help_text='Discord channel ID to copy permission overwrites from when creating/switching to this profile. Leave blank to inherit from the trigger channel.', null=True),
        ),
    ]
