# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disfunction', '0012_nomination_message_id_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distinctionlevel',
            options={'default_permissions': (), 'ordering': ['level'], 'verbose_name': 'Distinction Level', 'verbose_name_plural': 'Distinction Levels'},
        ),
        migrations.AlterModelOptions(
            name='eventattendance',
            options={'default_permissions': (), 'ordering': ['-actual_start']},
        ),
        migrations.AlterModelOptions(
            name='eventattendancerecord',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='eventreference',
            options={'default_permissions': (), 'verbose_name': 'Event Reference', 'verbose_name_plural': 'Event References'},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('can_approve_nominations', 'Can approve or deny nominations'), ('can_submit_nominations', 'Can submit nominations for members')], 'verbose_name': 'Nomination', 'verbose_name_plural': 'Nominations'},
        ),
        migrations.AlterModelOptions(
            name='protectedchannelack',
            options={'default_permissions': (), 'verbose_name': 'Protected Channel Acknowledgement', 'verbose_name_plural': 'Protected Channel Acknowledgements'},
        ),
        migrations.AlterModelOptions(
            name='temporaryvoicechannel',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'verbose_name': 'Temporary Voice Channel', 'verbose_name_plural': 'Temporary Voice Channels'},
        ),
        migrations.AlterModelOptions(
            name='userdistinction',
            options={'default_permissions': (), 'verbose_name': 'User Distinction', 'verbose_name_plural': 'User Distinctions'},
        ),
        migrations.AlterModelOptions(
            name='userjoinrecord',
            options={'default_permissions': (), 'ordering': ['-joined_at'], 'verbose_name': 'User Join Record', 'verbose_name_plural': 'User Join Records'},
        ),
        migrations.AlterModelOptions(
            name='vcrolepermission',
            options={'default_permissions': (), 'ordering': ['discord_role_id'], 'verbose_name': 'VC Role Permission', 'verbose_name_plural': 'VC Role Permissions'},
        ),
        migrations.AlterModelOptions(
            name='voiceactivitysummary',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='voiceban',
            options={'default_permissions': (), 'permissions': [('can_manage_voice_bans', 'Can manage voice bans via bot commands')]},
        ),
        migrations.AlterModelOptions(
            name='voicechannelprofile',
            options={'default_permissions': (), 'ordering': ['sort_order'], 'verbose_name': 'Voice Channel Profile', 'verbose_name_plural': 'Voice Channel Profiles'},
        ),
        migrations.AlterModelOptions(
            name='voicesession',
            options={'default_permissions': (), 'ordering': ['-join_time']},
        ),
        migrations.AlterModelOptions(
            name='voicesessioncheckpoint',
            options={'default_permissions': (), 'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='nomination',
            name='approval_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
