# Generated by Django 6.0.5 on 2026-05-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disfunction', '0013_alter_distinctionlevel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporaryvoicechannel',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('can_manage_temp_vcs', 'Can manage any temporary voice channel (override creator requirement)')], 'verbose_name': 'Temporary Voice Channel', 'verbose_name_plural': 'Temporary Voice Channels'},
        ),
    ]
