# Generated by Django 6.0.5 on 2026-05-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disfunction', '0014_can_manage_temp_vcs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomination',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('can_approve_nominations', 'Can approve or deny nominations'), ('can_submit_nominations', 'Can submit nominations for members'), ('can_self_nominate', 'Can submit a self-nomination for distinction')], 'verbose_name': 'Nomination', 'verbose_name_plural': 'Nominations'},
        ),
    ]
