# Generated by Django 6.0.5 on 2026-05-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disfunction', '0015_can_self_nominate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(db_index=True)),
                ('channel_name', models.CharField(max_length=100)),
                ('guild_id', models.BigIntegerField()),
                ('creator_id', models.BigIntegerField()),
                ('profile_slug', models.CharField(blank=True, max_length=50, null=True)),
                ('channel_type', models.CharField(max_length=10)),
                ('vc_created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('message_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'VC Transcript',
                'verbose_name_plural': 'VC Transcripts',
                'ordering': ['-deleted_at'],
                'permissions': [('view_vctranscript', 'Can view VC transcripts')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['guild_id', 'deleted_at'], name='disfunction_guild_i_b1abf3_idx'), models.Index(fields=['creator_id'], name='disfunction_creator_5e4bcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='VCTranscriptMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('author_id', models.BigIntegerField()),
                ('author_name', models.CharField(max_length=200)),
                ('author_avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('embeds_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disfunction.vctranscript')),
            ],
            options={
                'verbose_name': 'VC Transcript Message',
                'verbose_name_plural': 'VC Transcript Messages',
                'ordering': ['created_at'],
                'default_permissions': (),
            },
        ),
    ]
