# Generated by Django 6.0.5 on 2026-05-07 19:01

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_discord_id', models.BigIntegerField(db_index=True)),
                ('requested_by_discord_id', models.BigIntegerField()),
                ('resolved_by_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('specialty_key', models.CharField(db_index=True, max_length=60)),
                ('specialty_label', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('pilot', 'Pilot'), ('infantry', 'Infantry'), ('crewman', 'Crewman'), ('tradesman', 'Support')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], db_index=True, default='PENDING', max_length=10)),
                ('approval_channel_message_id', models.BigIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSpecialtyGrant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('recipient_discord_id', models.BigIntegerField(db_index=True)),
                ('requested_by_discord_id', models.BigIntegerField()),
                ('resolved_by_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('specialty_key', models.CharField(db_index=True, max_length=60)),
                ('specialty_label', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('pilot', 'Pilot'), ('infantry', 'Infantry'), ('crewman', 'Crewman'), ('tradesman', 'Support')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], db_index=True, default='PENDING', max_length=10)),
                ('approval_channel_message_id', models.BigIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical specialty grant',
                'verbose_name_plural': 'historical specialty grants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
