# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalreminder',
            options={'default_permissions': (), 'ordering': ['remind_at']},
        ),
        migrations.AlterModelOptions(
            name='leadergoal',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('manage_leader_goals', 'Can create, edit, and complete leader goals'), ('view_leader_goals', 'Can view leader goals')]},
        ),
        migrations.AlterModelOptions(
            name='orggoal',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('manage_org_goals', 'Can create, edit, and complete org goals'), ('view_org_goals', 'Can view org goals')]},
        ),
    ]
