# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilotboard', '0006_pilot_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalnote',
            options={'default_permissions': (), 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='pilot',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('view_pilot_roster', 'Can view the pilot roster'), ('manage_pilot_roster', 'Can add/edit/delete pilots and goals')]},
        ),
        migrations.AlterModelOptions(
            name='pilotgoal',
            options={'default_permissions': (), 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='pilotgroupfilter',
            options={'default_permissions': (), 'ordering': ['order', 'group__name'], 'verbose_name': 'Roster Group Filter', 'verbose_name_plural': 'Roster Group Filters'},
        ),
    ]
