# Generated by Django 6.0 on 2026-04-21 18:30

import app.killtracker.models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blacklist entries',
                'db_table': 'killtracker_blacklist',
            },
        ),
        migrations.CreateModel(
            name='GameModeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode_key', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('channel_id', models.BigIntegerField()),
                ('is_default', models.BooleanField(default=False, help_text='Fallback if no key matches')),
            ],
            options={
                'db_table': 'killtracker_gamemode_channel',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=app.killtracker.models._gen_key, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('is_permanent', models.BooleanField(default=False)),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killtracker_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'killtracker_apikey',
                'ordering': ['-created_at'],
                'permissions': [('can_generate_key', 'Can generate a KillTracker API key'), ('can_view_leaderboard', 'Can view the KillTracker leaderboard'), ('can_manage_aliases', 'Can manage KillTracker player aliases')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalApiKey',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=app.killtracker.models._gen_key, max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('is_permanent', models.BooleanField(default=False)),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical api key',
                'verbose_name_plural': 'historical api keys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPlayerAlias',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('game_name', models.CharField(db_index=True, max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical player alias',
                'verbose_name_plural': 'historical Player aliases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PlayerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killtracker_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Player aliases',
                'db_table': 'killtracker_player_alias',
            },
        ),
        migrations.CreateModel(
            name='KillEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killer_name', models.CharField(db_index=True, max_length=64)),
                ('victim', models.CharField(db_index=True, max_length=64)),
                ('game_mode', models.CharField(default='SC_Default', max_length=64)),
                ('weapon', models.CharField(blank=True, default='', max_length=128)),
                ('zone', models.CharField(blank=True, default='', max_length=128)),
                ('killers_ship', models.CharField(blank=True, default='', max_length=128)),
                ('client_ver', models.CharField(blank=True, default='', max_length=16)),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('victim_org', models.CharField(blank=True, default='', max_length=128)),
                ('victim_org_sid', models.CharField(blank=True, default='', max_length=32)),
                ('victim_avatar', models.URLField(blank=True, default='')),
                ('victim_enlisted', models.CharField(blank=True, default='', max_length=32)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='killtracker.apikey')),
                ('killer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='killtracker_kills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'killtracker_kill_event',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['killer', '-time'], name='killtracker_killer__b18640_idx'), models.Index(fields=['game_mode', '-time'], name='killtracker_game_mo_0a6556_idx')],
                'constraints': [models.UniqueConstraint(fields=('killer_name', 'victim', 'time', 'game_mode'), name='killtracker_dedupe')],
            },
        ),
    ]
