# Generated by Django 6.0 on 2026-04-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='If true, expiry is extended each time the key is used.'),
        ),
        migrations.AddField(
            model_name='historicalapikey',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='If true, expiry is extended each time the key is used.'),
        ),
    ]
