# Generated by Django 6.0 on 2026-04-21 22:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0002_apikey_auto_renew_historicalapikey_auto_renew'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSIProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('org_name', models.CharField(blank=True, default='', max_length=128)),
                ('org_short', models.CharField(blank=True, default='', max_length=32)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('enlisted_date', models.CharField(blank=True, default='', max_length=32)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'killtracker_rsi_profile_snapshot',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRSIProfileSnapshot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('handle', models.CharField(db_index=True, max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('org_name', models.CharField(blank=True, default='', max_length=128)),
                ('org_short', models.CharField(blank=True, default='', max_length=32)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('enlisted_date', models.CharField(blank=True, default='', max_length=32)),
                ('first_seen_at', models.DateTimeField(blank=True, editable=False)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rsi profile snapshot',
                'verbose_name_plural': 'historical rsi profile snapshots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
