# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0003_rsiprofilesnapshot_historicalrsiprofilesnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('can_generate_key', 'Can generate a KillTracker API key'), ('can_view_leaderboard', 'Can view the KillTracker leaderboard'), ('can_manage_aliases', 'Can manage KillTracker player aliases')]},
        ),
        migrations.AlterModelOptions(
            name='blacklistentry',
            options={'default_permissions': (), 'verbose_name_plural': 'Blacklist entries'},
        ),
        migrations.AlterModelOptions(
            name='gamemodechannel',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='killevent',
            options={'default_permissions': (), 'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='playeralias',
            options={'default_permissions': (), 'verbose_name_plural': 'Player aliases'},
        ),
        migrations.AlterModelOptions(
            name='rsiprofilesnapshot',
            options={'default_permissions': ()},
        ),
    ]
