# Generated by Django 6.0.5 on 2026-06-30 20:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0008_deviceauthrequest_device_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Shown in client logs; bump on every change so clients pick it up.', max_length=64, unique=True)),
                ('source', models.TextField(help_text='Full Python source for modules/sc_parser.py — must define GameLogParser and Event.')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'killtracker_parser_release',
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HistoricalParserRelease',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.CharField(db_index=True, help_text='Shown in client logs; bump on every change so clients pick it up.', max_length=64)),
                ('source', models.TextField(help_text='Full Python source for modules/sc_parser.py — must define GameLogParser and Event.')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical parser release',
                'verbose_name_plural': 'historical parser releases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
