# Generated by Django 6.0.5 on 2026-07-02 22:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0011_killevent_victim_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(max_length=64)),
                ('substring', models.CharField(max_length=128)),
                ('message', models.CharField(help_text='Logged client-side when this rule drops a kill.', max_length=256)),
            ],
            options={
                'db_table': 'killtracker_exclusion_rule',
                'ordering': ['game_mode', 'substring'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GameDataList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ignored_victim_substring', 'Ignored victim substring'), ('ignored_victim_prefix', 'Ignored victim prefix'), ('ship_manufacturer_prefix', 'Ship manufacturer prefix'), ('user_cfg_line', 'user.cfg required line'), ('free_flight_game_mode', 'Free Flight game mode key')], db_index=True, max_length=32)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'killtracker_game_data_list',
                'ordering': ['category', 'value'],
                'default_permissions': (),
                'unique_together': {('category', 'value')},
            },
        ),
        migrations.CreateModel(
            name='GameDataMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('weapon', 'Weapon name'), ('ship', 'Ship / zone name'), ('part_map', 'Body part ID -> zone'), ('process_name', 'OS process name'), ('contract_pattern', 'Contract log regex'), ('rsi_selector', 'RSI profile CSS selector')], db_index=True, max_length=32)),
                ('key', models.CharField(max_length=256)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'killtracker_game_data_mapping',
                'ordering': ['category', 'key'],
                'default_permissions': (),
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalExclusionRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('game_mode', models.CharField(max_length=64)),
                ('substring', models.CharField(max_length=128)),
                ('message', models.CharField(help_text='Logged client-side when this rule drops a kill.', max_length=256)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical exclusion rule',
                'verbose_name_plural': 'historical exclusion rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGameDataList',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(choices=[('ignored_victim_substring', 'Ignored victim substring'), ('ignored_victim_prefix', 'Ignored victim prefix'), ('ship_manufacturer_prefix', 'Ship manufacturer prefix'), ('user_cfg_line', 'user.cfg required line'), ('free_flight_game_mode', 'Free Flight game mode key')], db_index=True, max_length=32)),
                ('value', models.CharField(max_length=256)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical game data list',
                'verbose_name_plural': 'historical game data lists',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGameDataMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(choices=[('weapon', 'Weapon name'), ('ship', 'Ship / zone name'), ('part_map', 'Body part ID -> zone'), ('process_name', 'OS process name'), ('contract_pattern', 'Contract log regex'), ('rsi_selector', 'RSI profile CSS selector')], db_index=True, max_length=32)),
                ('key', models.CharField(max_length=256)),
                ('value', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical game data mapping',
                'verbose_name_plural': 'historical game data mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
