"""Seed GameDataMapping / GameDataList / ExclusionRule from the values that used to live as
hardcoded Python constants in game_data.py (and, for partMap/processNames/freeFlightGameModes/
contractPatterns/rsiSelectors, values that used to be hardcoded on the DESKTOP CLIENT). Moving
these to the DB means an admin edit takes effect immediately — no code deploy, no server
restart, and no desktop client release.

Data migrations must be self-contained (the app code these were copied from is free to change,
or lose these constants entirely, right after this migration is written) so every value is
inlined here rather than imported from app.killtracker.game_data.
"""
from django.db import migrations

WEAPON_MAPPING = {
    "Crash": "Ship Collision",
    "MRCK_S09_AEGS_Retaliator_Fore": "Argos IX Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_rt": "S10 Polaris Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_rb": "S10 Polaris Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_lb": "S10 Polaris Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_lt": "S10 Polaris Torpedo",
    "MRCK_S10_AEGS_Idris_Nose_S12_Torpedo": "S12 Idris Torpedo",
    "MRCK_S03_AEGS_Sabre_Firebird": "Thunderbolt III",
    "MISL_S02_IR_NOVP_Rattler": "S2 Rattler Missile",
    "MRCK_S01_Krig_quad": "S1 Missile",
    "MRCK_S03_BEHR_Quad_S01": "Pioneer I",
    "MRCK_S04_BEHR_Octo_S01": "Taskforce I",
    "MRCK_S03_BEHR_Dual_S02": "S2 Missile",
    "MRCK_S04_BEHR_Quad_S02": "S2 Missile",
    "MRCK_S05_VNCL_Stinger_S02": "S2 Missile",
    "MRCK_S05_VNCL_Stinger_S02_Right": "S2 Missile",
    "MRCK_S04_BEHR_Dual_S03": "S3 Missile",
    "BMBRCK_S03_BEHR_Single_S03": "S3 Thunderball Bomb",
    "BOMB_S03_FSKI_Thunderball": "S3 Thunderball Bomb",
    "BMBRCK_CRUS_Spirit_A1": "A1 Bomb",
    "BMBRCK_CRUS_STARL_Left": "A2 Bomb",
    "BMBRCK_CRUS_STARL_Right": "A2 Bomb",
    "KLWE_MassDriver_S10": "Tungsten Refrigerator",
    "HRST_LaserBeam_Bespoke": "The SUN",
    "RSI_Bespoke_BallisticCannon_A": "S6 Maris Ballistic Cannon",
    "BEHR_BallisticCannon_S7_Idris": "S7 Conqueror Ballistic Cannon",
    "KLWE_LaserRepeater_S1": "CF-117 Bulldog Repeater",
    "KLWE_LaserRepeater_S2": "CF-227 Badger Repeater",
    "KLWE_LaserRepeater_S3": "CF-337 Panther Repeater",
    "KLWE_LaserRepeater_S4": "CF-447 Rhino Repeater",
    "KLWE_LaserRepeater_S5": "CF-557 Galdereen Repeater",
    "KLWE_LaserRepeater_S6": "CF-667 Mammoth Repeater",
    "NONE_LaserRepeater_S1": "Ardor-1 Repeater",
    "NONE_LaserRepeater_S2": "Ardor-2 Repeater",
    "NONE_LaserRepeater_S3": "Ardor-3 Repeater",
    "HRST_LaserRepeater_S1": "Attrition-1 Repeater",
    "HRST_LaserRepeater_S2": "Attrition-2 Repeater",
    "HRST_LaserRepeater_S3": "Attrition-3 Repeater",
    "HRST_LaserRepeater_S4": "Attrition-4 Repeater",
    "HRST_LaserRepeater_S5": "Attrition-5 Repeater",
    "HRST_LaserRepeater_S6": "Attrition-6 Repeater",
    "MXOX_NeutronRepeater_S1": "S1 NDB-26 Repeater",
    "MXOX_NeutronRepeater_S2": "S2 NDB-28 Repeater",
    "MXOX_NeutronRepeater_S3": "S3 NDB-30 Repeater",
    "GLSN_BallisticGatling_S4": "S4 Breakneck Ballistic Gatling",
    "Krig_BallisticGatling_Bespoke_S4": "Relentless L-21 Ballistic Gatling",
    "KRON_LaserCannon_S3": "FL-33 Cannon",
    "AMRS_LaserCannon_S1": "S1 Omnisky III Cannon",
    "AMRS_LaserCannon_S2": "S2 Omnisky VI Cannon",
    "AMRS_LaserCannon_S3": "S3 Omnisky IX Cannon",
    "AMRS_LaserCannon_S4": "S4 Omnisky XII Cannon",
    "AMRS_LaserCannon_S5": "S5 Omnisky XV Cannon",
    "AMRS_LaserCannon_S6": "S6 Omnisky XVII Cannon",
    "APAR_MassDriver_S2": "Strife Mass Driver",
    "BEHR_BallisticGatling_S4": "AD4B Ballistic Gatling",
    "BEHR_BallisticGatling_S5": "AD5B Ballistic Gatling",
    "BEHR_BallisticGatling_S6": "AD6B Ballistic Gatling",
    "BEHR_LaserCannon_S3": "S3 M5A Cannon",
    "BEHR_LaserCannon_S4": "S4 M6A Cannon",
    "BEHR_LaserCannon_S5": "S5 M7A Cannon",
    "BEHR_LaserCannon_S7": "S7 M9A Cannon",
    "BEHR_LaserCannon_SF7E_S7": "S7 Ares Ion Cannon",
    "BEHR_BallisticGatling_S7": "S7 Ares Inferno Ballistic Gatling",
    "ESPR_BallisticCannon_S3": "Deadbolt III Cannon",
    "ESPR_BallisticCannon_S4": "Deadbolt IV Cannon",
    "ESPR_BallisticCannon_S5": "Deadbolt V Cannon",
    "GATS_BallisticGatling_S3": "S3 Mantis GT-220 Gatling",
    "GATS_BallisticCannon_S3 ": "S3 Tarantula GT-870 MkIII Cannon",
    "BEHR_BallisticGatling_Hornet_Bespoke": "MiniGun Go Burrr",
    "APAR_BallisticGatling_S4": "MinigGun Go Burrr",
    "KBAR_BallisticCannon_S3": "S3 11-Series Broadsword Cannon",
    "VNCL_LaserCannon_S2": "S2 WASP Repeater",
    "VNCL_PlasmaCannon_S2": "S2 WHIP Cannon",
    "VNCL_PlasmaCannon_S3": "S3 WARLORD Cannon",
    "VNCL_PlasmaCannon_S5": "S5 WRATH Cannon",
    "VNCL_Gen2_PlasmaCannon_S5": "S5 WRATH Cannon",
    "none_melee_01": "Dropped the Soap",
    "utfl_melee_01_red01_gungame": "I WON GUN GAME",
    "utfl_melee_01_gungame": "FSK-8 Combat Knife",
    "gmni_smg_ballistic_01": "C54 SMG",
    "gmni_smg_ballistic_01_Luminalia": "C54 Luminalia SMG",
    "gmni_smg_ballistic_01_green_grey01": "C54 Luckbringer SMG",
    "gmni_smg_ballistic_01_Justified": "C54 Justified SMG",
    "gmni_smg_ballistic_01_Scorched": "C54 Scorched SMG",
    "gmni_smg_ballistic_01_Starchaser": "C54 Starchaser SMG",
    "gmni_smg_ballistic_01_blue_white01": "C54 Origin Racing SMG",
    "behr_smg_ballistic": "P8-SC SMG",
    "behr_smg_ballistic_01": "P8-SC SMG",
    "behr_smg_ballistic_01_white02": "P8-SC Boneyard SMG",
    "behr_smg_ballistic_01_tan01": "P8-SC Desert Shadow SMG",
    "behr_smg_ballistic_01_gold01": "P8-SC Executive SMG",
    "behr_smg_ballistic_01_black01": "P8-SC Midnight SMG",
    "behr_smg_ballistic_01_black02": "P8-SC Nightstalker SMG",
    "behr_smg_ballistic_01_iae2201": "P8-SC Red Alert SMG",
    "behr_smg_ballistic_01_white01": "P8-SC Stormfall SMG",
    "behr_smg_ballistic_01_green01": "P8-SC  Warhawk SMG",
    "behr_rifle_ballistic_02_civilian": "P8-AR Rifle",
    "behr_rifle_ballistic_01_spc_01": "P8-AR Rifle",
    "behr_rifle_ballistic_01_white02": "P8-AR Rifle",
    "behr_rifle_ballistic_02_civilian_black01": "P8-AR Rifle",
    "behr_rifle_ballistic_02_military": "P8-AR Military Rifle",
    "behr_rifle_ballistic_02_P8SC": "P8-AR P8SC Rifle",
    "behr_rifle_ballistic_02_Scorched": "P8-AR Scorched Rifle",
    "behr_rifle_ballistic_02_Stalker": "P8-AR Stalker Rifle",
    "behr_rifle_ballistic_02_Warlord": "P8-AR Warlord Rifle",
    "behr_rifle_ballistic_02_civilian_blue01": "P8-AR CitizenCon 2954 Rifle",
    "behr_rifle_ballistic_01": "P4-AR Rifle",
    "behr_rifle_ballistic_01_black02": "P4-AR Nightstalker Rifle",
    "behr_rifle_ballistic_01_green01": "P4-AR Woodland Rifle",
    "behr_rifle_ballistic_01_red01": "P4-AR Red Alert Rifle",
    "behr_rifle_ballistic_01_white01": "P4-AR Arctic Rifle",
    "behr_rifle_ballistic_01_yellow01": "P4-AR Desert Strike Rifle",
    "ksar_rifle_energy_01": "Karna Rifle",
    "ksar_rifle_energy_01_pink_red01": "Hello Kitty Karna Rifle",
    "ksar_rifle_energy_01_red01": "Karna Brimstone Rifle",
    "ksar_rifle_energy_01_black01": "Karna Blackout Rifle",
    "ksar_rifle_energy_01_blue_gold": "Karna Valor Rifle",
    "ksar_rifle_energy_01_blue_gold_spc_01": "Karna Valor Rifle",
    "ksar_rifle_energy_01_iae2023": "Karna Ascension Rifle",
    "ksar_rifle_energy_01_firerats01_spc": "Karna Scorched Rifle",
    "ksar_rifle_energy_01_red_green01": "Karna Christmas Rifle",
    "behr_lmg_ballistic_01": "FS-9",
    "behr_lmg_ballistic_01_yellow_grey01": "FS-9 Yellow LMG",
    "behr_lmg_ballistic_01_green01": "FS-9 Woodland LMG",
    "behr_lmg_ballistic_01_black01": "FS-9 Nightstalker LMG",
    "behr_lmg_ballistic_01_red01": "FS-9 Inferno LMG",
    "behr_lmg_ballistic_01_blue01": "FS-9 Oceanic LMG",
    "behr_lmg_ballistic_01_xenothreat01": "FS-9 Stoneface LMG",
    "klwe_lmg_energy_01": "Demeco LMG",
    "klwe_lmg_energy_01_purple_blue01": "Demeco Purple LMG",
    "klwe_lmg_energy_01_iae2201": "Demeco IAE LMG",
    "gmni_lmg_ballistic_01_blue_gold": "F55 LMG",
    "gmni_lmg_ballistic_01": "F55 LMG",
    "gmni_lmg_ballistic_01_green_red01": "Christmas F55 LMG",
    "gmni_lmg_ballistic_01_firerats01": "Scorched F55 LMG",
    "ksar_shotgun_energy_01_gold01": "Devastator Executive Shotgun",
    "ksar_shotgun_energy_01": "Devastator Shotgun",
    "gmni_rifle_ballistic_01": "S71 Rifle",
    "gmni_rifle_ballistic_01_firerats01": "S71 Bullseye Rifle",
    "gmni_pistol_ballistic_01": "LH86 Pistol",
    "gmni_pistol_ballistic_01_blue_white01": "LH86 Permafrost Pistol",
    "gmni_pistol_ballistic_01_green01": "LH86 Green Pistol",
    "behr_pistol_ballistic_01": "S-38 Pistol",
    "ksar_pistol_ballistic_01": "Coda Revolver",
    "hdgw_pistol_ballistic_01": "Salvo Frag Pistol",
    "hdgw_pistol_ballistic_01_engraved01": "Salvo Saeed Frag Pistol",
    "klwe_pistol_energy_01": "Arclight Pistol",
    "lbco_pistol_energy_01": "Yurabrev Pistol",
    "volt_smg_energy_01": "Quartz Energy SMG",
    "volt_smg_energy_01_tint01_optic": "Quartz Energy SMG",
    "volt_smg_energy_01_tint02": "Quartz Energy SMG",
    "volt_smg_energy_01_tint02_optic": "Quartz Energy SMG",
    "volt_smg_energy_01_tint03": "Quartz Energy SMG",
    "volt_smg_energy_01_store02": "Quartz Clawed Steel Energy SMG",
    "volt_smg_energy_01_uee01": "Quartz Energy SMG",
    "volt_smg_energy_01_store01": "Quartz True Valor Energy SMG",
    "volt_rifle_energy_01": "Volt Parallax Rifle",
    "volt_rifle_energy_01_tint02": "Volt Parallax Rifle",
    "volt_rifle_energy_01_camo01": "Volt Parallax Shock Trooper Rifle",
    "volt_rifle_energy_01_black_gold01": "Volt Parallax Downburst Rifle",
    "volt_shotgun_energy_01_tint01": "Volt Parallax Shotgun",
    "volt_shotgun_energy_01": "Volt Parallax Shotgun",
    "volt_shotgun_energy_01_tint03": "Volt Parallax Shotgun",
    "volt_sniper_energy_01_tint02": "Zenith Laser Sniper Rifle",
    "volt_lmg_energy_01_tint02": "Volt Fresnel LMG",
    "behr_shotgun_ballistic_01": "BR-2 Shotgun",
    "klwe_rifle_energy_01": "Gallant Rifle",
    "klwe_rifle_energy_01_green01": "Gallant Scrubland Rifle",
    "klwe_rifle_energy_01_black01": "Gallant Midnight Rifle",
    "klwe_smg_energy_01_blue_gold": "Lumin V Invictus SMG",
    "klwe_smg_energy_01": "Lumin V SMG",
    "gmni_shotgun_ballistic_01_pink_red01": "R97 Red Alert Shotgun",
    "gmni_shotgun_ballistic_01": "R97 Shotgun",
    "behr_sniper_ballistic_01": "P6-LR Rifle",
    "behr_sniper_ballistic_01_black01": "P6-LR Black Rifle",
    "behr_sniper_ballistic_01_arctic01": "P6-LR Rime Rifle",
    "ksar_sniper_ballistic_01": "Scalpel Sniper Rifle",
    "ksar_sniper_ballistic_01_white_blue_01": "Scalpel Permafrost Sniper Rifle",
    "gmni_sniper_ballistic_01": "AO3 Rifle",
    "gmni_sniper_ballistic_01_iae2201": "A03 Red Alert Rifle",
    "gmni_sniper_ballistic_01_firerats01": "A03 Scorched Rifle",
    "none_lmg_ballistic": "Pulverizer Payback LMG",
    "none_lmg_ballistic_01": "Pulverizer Payback LMG",
    "none_lmg_ballistic_01_store01": "Pulverizer Payback LMG",
    "none_rifle_multi": "Space AK",
    "none_rifle_multi_01": "Space AK",
    "none_rifle_multi_01_store01": "Space AK",
    "behr_glauncher_ballistic_01": "Grenade Launcher",
    "ksar_shotgun_ballistic_01": "Ravager Shotgun",
    "ksar_smg_energy_01": "Custodian SMG",
    "ksar_smg_energy_01_black01": "Custodian SMG",
    "none_shotgun_ballistic_01": "Deadrig Shotgun",
    "HRST_Nova_BallisticCannon_S5": "Kentucky windage",
    "HRST_Storm_LaserRepeater_S3": "Pee Shooter",
    "apar_special_ballistic_01": "Railgun",
    "apar_special_ballistic_02": "Animus Missile Launcher",
}

SHIP_MAPPING = {
    "p2l4_contestedzone": "Contested Zone",
    "ab_pyro_int_dung": "Security Keycard Zone Interior",
    "OOC_Stanton_2a_Cellin": "Security Post Kareah",
    "rs_opendungeon_rund": "Ruin Contested Zone Ghost Arena",
    "p5l2_contestedzone": "Contested Zone",
    "OOC_Stanton_2c_Yela": "Yela",
    "P3_L5": "PYAM-SUPVISR-3-5",
    "ab_pyro_int_dung_exec": "Executive Hangers",
    "rs_cz_rewards": "CZ Loot Room",
    "orbtl_002_plat_001_util_a_orbital_001_occu_a_final": "Hathor OLP",
    "asd_labresearch_int_01a": "Lazarus Complex",
    "ht_xs_003_occu_a_final_int_b-001": "Lazarus Complex",
    "t_xs_003_occu_a_final_int_b-002": "Lazarus Complex",
    "ht_xs_003_occu_a_final_int_b-003": "Lazarus Complex",
    "ht_xs_003_occu_a_final_int_b-004": "Lazarus Complex",
    "ht_station_001_occu_a_final_int": "Lazarus Complex",
    "ht_xs_003_occu_a_final_int_b": "Lazarus Complex",
    "TransitCarriage_ASD_Shuttle_A": "Lazarus Shuttle",
    "asd_labdata_int_01a": "Farro Data Center",
    "OC_Nose_med_sfce_ctpl_g": "Caterpillar Wreck",
    "OOC_Stanton_4_Microtech": "Microtech",
    "OOC_Stanton_1a_Ariel": "Arial",
    "layout_int_power": "ASD Facilities",
    "layout_int_science": "ASD Facilities",
    "TransitCarriage_elev_util_very_fast": "ASD Facilities",
    "OOC_Stanton_1_Hurston": "Dupree Industrial Manufacturing Facility",
    "int_s1_dc_dpre_imf": "Dupree Industrial Manufacturing Facility",
    "POWR_TYDT_S01_Slipstream_SCItem": "Slipstream OP",
    "ObjectContainer-0002_INT": "Prison",
    "TransitCarriage_Reststop_Small": "Elevator Combat",
    "Hangar_MediumFront_RestStop_Pyro": "Hanger PVP",
    "Hangar_SmallFront_RestStop_Pyro": "Hanger PVP",
    "Hangar_LargeTop_RestStop_Pyro": "Hanger PVP",
    "Hangar_XLTop_Lorville": "Hanger PVP",
    "rs_int_p3l1": "Starlight Station PVP",
    "Hangar_SmallFront_GrimHEX": "GrimHex Small Hanger PVP",
    "util_a_orbital_001_occu_a_final-001": "OLP PVP",
    "OOC_Stanton_2b_Daymar": "Daymar PVP",
    "TransitCarriage_elev_util": "Elevator PVP",
    "Hangar_LargeFront_GrimHEX": "GrimHex Large Hanger PVP",
    "Hangar_XLTop_Orison": "Orison Hanger PVP",
    "util_dish_001_rund_a_final_int": "Hathor Ground Station",
    "util_a_orbital_001_occu_a_final_int": "Hathor Orbital Station",
    "util_cmpd_wrhse_lge_001_rund_c_final_int": "Hathor Large Warehouse",
    "util_cmpd_wrhse_sml_001_rund_c_final_int": "Hathor Small Warehouse",
    "util_cmpd_wrhse_lge_001_rund_a_final_int": "Hathor Warehouse",
    "RastarInteriorGridHost": "Outpost Buildings",
    "OOC_Stanton_2_Crusader": "Crusader System",
    "OOC_Stanton_1b_Aberdeen": "Aberdeen",
    "sand01_vlk_001_001_int": "Valakkar Cave",
    "AEGS_Avenger_Stalker": "Avenger Stalker",
    "AEGS_Avenger_Titan": "Avenger Titan",
    "AEGS_Eclipse": "Eclipse",
    "AEGS_Gladius": "Gladius",
    "AEGS_Gladius_PIR": "Gladius Pirate",
    "AEGS_Gladius_Valiant": "Gladius Valiant",
    "AEGS_Hammerhead": "Hammerhead",
    "AEGS_Redeemer": "Redeemer",
    "AEGS_Retaliator": "Retaliator",
    "AEGS_Sabre": "Sabre",
    "AEGS_Sabre_Comet": "Sabre Comet",
    "AEGS_Sabre_Firebird": "Sabre Firebird",
    "AEGS_Sabre_Raven": "Sabre Raven",
    "AEGS_Vanguard_Harbinger": "Vanguard Harbinger",
    "AEGS_Vanguard_Sentinel": "Vanguard Sentinel",
    "AEGS_Vanguard_Hoplite": "Vanguard Hoplight",
    "AEGS_Reclaimer": "Dog Microwaver",
    "AEGS_Reclaimer_Showdown": "Dog Microwaver BIS",
    "AEGS_Idris_P": "Peacekeeper Idris-P",
    "AEGS_Idris_M": "Military Idris-M",
    "TransitCarriage_AEGS_Idris_Cargo_Elevator": "Idris-P Interior",
    "ANVL_Arrow": "Arrow",
    "ANVL_Paladin": "Paladin",
    "ANVL_C8X_Pisces_Expedition": "C8X Pisces Expedition",
    "ANVL_C8R_Pisces": "C8R Pisces",
    "ANVL_C8_Pisces": "C8 Pisces",
    "ANVL_C8_Pisces_Tutorial": "C8 Pisces Tutorial",
    "ANVL_Terrapin_Medic": "Terrapin Medic",
    "ANVL_Terrapin": "Terrapin",
    "ANVL_Carrack": "Carrack",
    "ANVL_Ballista": "Ballista",
    "ANVL_Carrack_Expedition": "Carrack Expedition",
    "ANVL_Hornet_F7A_Mk1": "F7C-M Super Hornet Mk I",
    "ANVL_Hornet_F7CM": "F7C-M Super Hornet Mk I",
    "ANVL_Hornet_F7C_Mk2": "Hornet F7C MKII",
    "ANVL_Hornet_F7A_Mk2": "Hornet F7A MKII",
    "ANVL_Hornet_F7CR_Mk2": "Hornet F7C MKII",
    "ANVL_Hornet_F7CM_Mk2": "Hornet F7CM MKII",
    "ANVL_Hornet_F7CM_Heartseeker": "Hornet F7CM Heartseeker MKI",
    "ANVL_Hornet_F7A_Mk2_Exec_Stealth": "Hornet F7A MKII Executive Stealth",
    "ANVL_Hornet_F7A_Mk2_Exec_Military": "Hornet F7A MKII Executive Military",
    "ANVL_Hornet_F7C_Wildfire": "F7C Hornet MKI Wildfire ",
    "ANVL_Hornet_F7CS_Mk1": "Hornet F7CS MKI Ghost",
    "ANVL_Hornet_F7CS_Mk2": "Hornet F7CS MKII Ghost",
    "ANVL_Hornet_F7CS": "Hornet F7C-S MKI Ghost ",
    "ANVL_Lightning_F8C": "F8C Lightning",
    "ANVL_Lightning_F8C_Exec": "F8C Lightning Executive",
    "ANVL_Lightning_F8C_Exec_Stealth": "F8C Lighting Executive Stealth",
    "ANVL_Gladiator": "Gladiator",
    "ANVL_Valkyrie": "Valkyrie",
    "ANVL_Hawk": "Hawk",
    "ANVL_Hurricane": "Hurricane",
    "ANVL_Asgard": "Asgard",
    "XNAA_SanTokYai": "San'tok.yai",
    "XIAN_Scout": "Khartu-al",
    "ARGO_RAFT": "Argo Raft",
    "ARGO_MOLE": "Mole",
    "BANU_Defender": "Banu Defender",
    "CNOU_Mustang_Alpha": "Mustang Alpha",
    "CNOU_Mustang_Delta": "Mustang Delta",
    "CNOU_Nomad": "Nomad",
    "CRUS_Spirit_A1": "Spirit A1",
    "CRUS_Starlifter_A2": "Hercules A2",
    "CRUS_Starfighter_Inferno": "Ares Inferno",
    "CRUS_Starfighter_Ion": "Ares Ion",
    "CRUS_Starfighter_Ino": "Ares Ion",
    "CRUS_Spirit_C1": "Spirit C1",
    "CRUS_Starlifter_C2": "Hercules C2",
    "CRUS_Intrepid": "Intredpid",
    "CRUS_Starlifter_M2": "Hercules M2",
    "CRUS_Star_Runner": "Mercury Star Runner",
    "DRAK_Buccaneer": "Buccaneer",
    "DRAK_Caterpillar": "Caterpillar",
    "DRAK_Caterpillar_Pirate": "Caterpillar Pirate",
    "DRAK_Corsair": "Corsair",
    "DRAK_Corsair_Exec_Military": "Corsair Executive Miltary",
    "DRAK_Cutlass_Black": "Cutlass Black",
    "DRAK_Cutlass_Blue": "Cutlass Blue",
    "DRAK_Cutlass_Red": "Cutlass Red",
    "DRAK_Cutlass_Steel": "Cutlass Steel",
    "DRAK_Cutlass_Black_Exec_Military": "Cutlass Black Executive Military",
    "DRAK_Cutlass_Black_Exec_Stealth": "Cutlass Black Executive Stealth",
    "DRAK_Cutlass_Black_ShipShowdown": "Cutlass Black BIS",
    "DRAK_Cutter": "Cutter",
    "DRAK_Cutter_Rambler": "Cutter Rambler",
    "DRAK_Cutter_Scout": "Cutter Scout",
    "DRAK_Vulture": "Vulture",
    "DRAK_Herald": "Herald",
    "DRAK_Golem": "Golem",
    "ESPR_Talon": "Talon",
    "ESPR_Prowler_Utility": "Prowler Utility",
    "ESPR_Prowler": "Prowler",
    "VNCL_Glaive": "Glaive(Replica)",
    "GAMA_Syulen": "Syulen",
    "GAMA_Syulen_Exec_Stealth": "Syulen Executive Stealth",
    "GLSN_Shiv": "Grey's Market Shiv",
    "KRIG_P52_Merlin": "P52 Merlin",
    "KRIG_P72_Archimedes": "P72 Archimedes",
    "KRIG_L21_Wolf": "L-21 Wolf",
    "MISC_Fury": "Fury",
    "MRAI_Pulse": "Pulse",
    "MRAI_Guardian": "Guardian",
    "MRAI_Guardian_military": "Guardian Vault Military",
    "MRAI_Guardian_QI": "Guardian QI",
    "MRAI_Guardian_MX": "Guardian MX",
    "MISC_Freelancer": "Freelancer",
    "MISC_Freelancer_MAX": "Freelancer MAX",
    "MISC_Freelancer_DUR": "Freelancer DUR",
    "MISC_Hull_A": "Hull A",
    "MISC_Hull_C": "Hull C",
    "MISC_Prospector": "Prospector",
    "MISC_Reliant_Tana": "Reliant Tana",
    "MISC_Starlancer_TAC": "Starlancer TAC",
    "MISC_Starlancer_Max": "Starlancer MAX",
    "MISC_Razor_EX": "Razor EX",
    "MISC_Starfarer": "Starfarer",
    "MISC_Reliant": "Reliant",
    "ORIG_m50": "M50",
    "ORIG_300i": "300i",
    "ORIG_315p": "315p",
    "ORIG_125a": "125a",
    "ORIG_400i": "400i",
    "ORIG_600i_Touring": "600i Touring",
    "ORIG_X1_Force": "X1 Force",
    "ORIG_890Jump": "890 Mr MoneyBags",
    "RSI_Aurora_CL": "Aurora CL",
    "RSI_Aurora_ES": "Aurora ES",
    "RSI_Aurora_LN": "Aurora LN",
    "RSI_Aurora_LX": "Aurora LX",
    "RSI_Aurora_MR": "Aurora MR",
    "RSI_Constellation_Andromeda": "Constellation Andromeda",
    "RSI_Constellation_Aquila": "Constellation Aquila",
    "RSI_Constellation_Taurus": "Constellation Taurus",
    "RSI_Constellation_Phoenix": " Constellation Phoenix",
    "RSI_Constellation_Phoenix_Emerald": "Constellation Phoenix Emerald",
    "RSI_Constellation_Taurus_military": "Constellation Taurus Vault Spec",
    "RSI_Mantis": "Mantis",
    "RSI_Ursa_Medivac": "Ursa Medivac",
    "RSI_Polaris": "Polaris",
    "RSI_Com_TP": "Polaris",
    "RSI_Polaris_Collector_Military": "Polaris Wikelo",
    "RSI_Apollo_Medivac": "Apollo Medivac",
    "RSI_Scorpius": "Scorpius",
    "RSI_Scorpius_Antares": "Scorpius Antares",
    "rsi_scorpius_militarty": "Scorpius Vault Spec",
    "RSI_Zeus_CL": "Zeus CL",
    "RSI_Zeus_ES": "Zeus ES",
    "RSI_Meteor": "Meteor",
    "VNCL_Blade": "Blade",
    "VNCL_Scythe_EA_AI_VAN_Alpha": "Vanduul Scythe",
    "VNCL_Scythe": "Vanduul Scythe",
    "VNCL_Stinger": "Stinger",
    "TMBL_Storm": "Storm 'Smol' Tonk",
    "TMBL_Nova": "Nova 'Thick' Tonk",
}

IGNORED_VICTIM_SUBSTRINGS = ("kopion", "marok", "pu_human", "pc_archetypes", "pu_pilots")
IGNORED_VICTIM_PREFIXES = ("quasigrazer", "shipjacker", "argo_atls")
SHIP_MANUFACTURER_PREFIXES = (
    "DRAK", "ORIG", "AEGS", "ANVL", "CRUS", "BANU", "MISC",
    "KRIG", "XNAA", "ARGO", "VNCL", "ESPR", "RSI", "CNOU",
    "GRIN", "TMBL", "GAMA",
)
USER_CFG_LINES = (
    "log_Verbosity = 2",
    "log_WriteToFileVerbosity = 2",
    "g_combatLogging.allowLogging = 1",
    "g_combatLogging.recordingMode = 1",
    "g_LogDamage = 1",
    "g_combat_stats_analytics_enabled = 1",
)
EXCLUSION_RULES = (
    {"game_mode": "EA_FreeFlight", "substring": "Crash", "message": "Probably a ship reset, ignoring kill!"},
    {"game_mode": "EA_FreeFlight", "substring": "SelfDestruct", "message": "Self-destruct detected in Free Flight, ignoring kill!"},
    {"game_mode": "EA_SquadronBattle", "substring": "Crash", "message": "Crash detected in Squadron Battle, ignoring kill!"},
    {"game_mode": "EA_SquadronBattle", "substring": "SelfDestruct", "message": "Self-destruct detected in Squadron Battle, ignoring kill!"},
)

# Below: values that used to be hardcoded on the DESKTOP CLIENT (modules/sc_parser.py,
# modules/kill_tracker.py, modules/log_parser.py, modules/contract_tracker.py,
# modules/rsi_scraper.py) — moved here so the client no longer needs a release to fix them.

PART_MAP = {
    11: "head", 12: "head", 13: "head", 14: "head", 18: "head",
    0: "torso", 5: "torso", 8: "torso", 9: "torso", 10: "torso",
    3: "arms", 4: "arms", 6: "arms", 7: "arms",
    1: "legs", 2: "legs", 15: "legs", 16: "legs", 17: "legs",
}

PROCESS_NAMES = {
    "game": "StarCitizen_Launcher.exe",
    "rsi_launcher": "RSI Launcher.exe",
}

FREE_FLIGHT_GAME_MODES = ("EA_FreeFlight",)

CONTRACT_PATTERNS = {
    "pattern.timestamp": r"^<([0-9T:\-.Z]+)>",
    "pattern.marker": r"CreateMarker.*missionId \[([^\]]+)\].*generator name \[([^\]]+)\].*contract \[([^\]]+)\]",
    "pattern.marker_def_id": r"contractDefinitionId\[([^\]]+)\]",
    "pattern.accepted": r'Added notification "Contract Accepted:.*?MissionId: \[([^\]]+)\]',
    "pattern.end_mission": r"<EndMission>.*MissionId\[([^\]]+)\].*CompletionType\[(\w+)\].*Reason\[([^\]]+)\]",
    "pattern.blueprint": r'Added notification "Received Blueprint: ([^:]+):',
    "label.Complete": "Contract complete",
    "label.Abandon": "Contract abandoned",
    "label.Fail": "Contract failed",
    "label.Disconnect": "Contract disconnected",
    "label.Deactivate": "Contract deactivated",
}

RSI_SELECTORS = {
    "citizen_url_template": "https://robertsspaceindustries.com/citizens/{}",
    "default_avatar_url": "https://cdn.robertsspaceindustries.com/static/images/account/avatar_default_big.jpg",
    "display_name": ".profile .info .entry .value",
    "avatar_img": ".profile .thumb img",
    "org_name": ".main-org .info .entry .value",
    "org_link": ".main-org .info a",
    "entry_row": ".entry",
    "entry_label": ".label",
    "entry_value": ".value",
}


def seed(apps, schema_editor):
    GameDataMapping = apps.get_model("killtracker", "GameDataMapping")
    GameDataList = apps.get_model("killtracker", "GameDataList")
    ExclusionRule = apps.get_model("killtracker", "ExclusionRule")

    mappings = []
    mappings += [GameDataMapping(category="weapon", key=k, value=v) for k, v in WEAPON_MAPPING.items()]
    mappings += [GameDataMapping(category="ship", key=k, value=v) for k, v in SHIP_MAPPING.items()]
    mappings += [GameDataMapping(category="part_map", key=str(k), value=v) for k, v in PART_MAP.items()]
    mappings += [GameDataMapping(category="process_name", key=k, value=v) for k, v in PROCESS_NAMES.items()]
    mappings += [GameDataMapping(category="contract_pattern", key=k, value=v) for k, v in CONTRACT_PATTERNS.items()]
    mappings += [GameDataMapping(category="rsi_selector", key=k, value=v) for k, v in RSI_SELECTORS.items()]
    GameDataMapping.objects.bulk_create(mappings)

    lists = []
    lists += [GameDataList(category="ignored_victim_substring", value=v) for v in IGNORED_VICTIM_SUBSTRINGS]
    lists += [GameDataList(category="ignored_victim_prefix", value=v) for v in IGNORED_VICTIM_PREFIXES]
    lists += [GameDataList(category="ship_manufacturer_prefix", value=v) for v in SHIP_MANUFACTURER_PREFIXES]
    lists += [GameDataList(category="user_cfg_line", value=v) for v in USER_CFG_LINES]
    lists += [GameDataList(category="free_flight_game_mode", value=v) for v in FREE_FLIGHT_GAME_MODES]
    GameDataList.objects.bulk_create(lists)

    ExclusionRule.objects.bulk_create([ExclusionRule(**r) for r in EXCLUSION_RULES])


def unseed(apps, schema_editor):
    apps.get_model("killtracker", "GameDataMapping").objects.all().delete()
    apps.get_model("killtracker", "GameDataList").objects.all().delete()
    apps.get_model("killtracker", "ExclusionRule").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("killtracker", "0012_exclusionrule_gamedatalist_gamedatamapping_and_more"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
