# Generated by Django 5.2.9 on 2026-01-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganicEvent",
            fields=[
                (
                    "thread_id",
                    models.BigIntegerField(
                        help_text="Discord Thread ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "embed_message_id",
                    models.BigIntegerField(
                        help_text="ID of the main dashboard message in the parent channel"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="e.g., DEATHWATCH, SCPVP", max_length=50
                    ),
                ),
                (
                    "starter_id",
                    models.BigIntegerField(
                        help_text="Discord User ID of the initiator"
                    ),
                ),
                ("voice_channel_id", models.BigIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "select_vc_msg_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID of the ephemeral warning message inside thread",
                        null=True,
                    ),
                ),
                (
                    "latest_summary_source_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
