# Generated by Django 6.0 on 2026-01-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_models', '0002_temporaryvoicechannel_userjoinrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingChannelClosure',
            fields=[
                ('channel_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guild_id', models.BigIntegerField()),
                ('status', models.CharField(help_text='Application status when closed', max_length=50)),
                ('applicant_id', models.BigIntegerField(blank=True, null=True)),
                ('processed_by', models.CharField(help_text='Staff who processed', max_length=100)),
                ('close_time', models.DateTimeField(help_text='When to close the channel')),
                ('transcript_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pending Channel Closure',
                'verbose_name_plural': 'Pending Channel Closures',
                'ordering': ['close_time'],
            },
        ),
        migrations.CreateModel(
            name='SquireTrialThread',
            fields=[
                ('status', models.CharField(choices=[('ACTV', 'Active'), ('SUCC', 'Succeeded'), ('DENY', 'Denied')], db_index=True, default='ACTV', max_length=4)),
                ('thread_id', models.BigIntegerField(help_text='Discord Thread ID', primary_key=True, serialize=False)),
                ('squire_id', models.BigIntegerField(help_text='Discord User ID of the subject squire')),
                ('initiator_id', models.BigIntegerField(blank=True, help_text='Discord User ID of the initiator', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptchaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(db_index=True)),
                ('session_token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('captcha_answer', models.CharField(max_length=100)),
                ('captcha_type', models.CharField(choices=[('TEXT', 'Text CAPTCHA'), ('MATH', 'Math CAPTCHA'), ('IMAGE', 'Image CAPTCHA')], default='TEXT', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When CAPTCHA expires')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CAPTCHA Session',
                'verbose_name_plural': 'CAPTCHA Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['discord_id', 'is_verified'], name='orm_models__discord_d7c7f6_idx'), models.Index(fields=['expires_at'], name='orm_models__expires_c7397f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.BigIntegerField(db_index=True, help_text='Discord ID of applicant')),
                ('application_type', models.CharField(choices=[('FULL', 'Full Member Application'), ('EXTERNAL', 'External Org Representative'), ('VISITOR', 'Visitor Only')], default='FULL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED_LEGION', 'Approved for Legion'), ('APPROVED_AUX', 'Approved for AUX'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('age', models.IntegerField(blank=True, help_text="Applicant's age", null=True)),
                ('rsi_profile_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rsi_handle', models.CharField(blank=True, help_text='RSI username/handle', max_length=100, null=True)),
                ('rsi_verified', models.BooleanField(default=False, help_text='RSI profile verification status')),
                ('gameplay_interests', models.TextField(blank=True, null=True)),
                ('play_time', models.CharField(blank=True, max_length=100, null=True)),
                ('heard_about', models.TextField(blank=True, help_text='How they heard about BlightVeil', null=True)),
                ('rules_agreement', models.BooleanField(default=False, help_text='Agrees to rules')),
                ('goal_selection', models.CharField(blank=True, choices=[('LEGION', 'Legion Member'), ('AUX', 'Auxiliary Member'), ('EXTERNAL', 'External Representative'), ('VISITOR', 'Visitor Only')], max_length=50, null=True)),
                ('external_org_name', models.CharField(blank=True, max_length=200, null=True)),
                ('external_org_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('application_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('reviewer_id', models.BigIntegerField(blank=True, help_text='ID of staff who reviewed', null=True)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('flags', models.JSONField(default=dict, help_text='Application flags and metadata')),
            ],
            options={
                'verbose_name': 'Membership Application',
                'verbose_name_plural': 'Membership Applications',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['applicant_id', 'status'], name='orm_models__applica_c342e8_idx'), models.Index(fields=['status', 'submitted_at'], name='orm_models__status_96cc48_idx'), models.Index(fields=['rsi_verified'], name='orm_models__rsi_ver_bdc90b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RSIVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(db_index=True)),
                ('rsi_handle', models.CharField(db_index=True, max_length=100)),
                ('verification_code', models.CharField(help_text='Code to place in RSI bio', max_length=100)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FAILED', 'Verification Failed'), ('EXPIRED', 'Verification Expired')], default='PENDING', max_length=20)),
                ('rsi_profile_url', models.URLField(max_length=500)),
                ('bio_screenshot', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='When verification expires')),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RSI Verification',
                'verbose_name_plural': 'RSI Verifications',
                'ordering': ['-created_at'],
                'unique_together': {('discord_id', 'rsi_handle')},
            },
        ),
    ]
