# Generated by Django 6.0 on 2026-01-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_models', '0003_pendingchannelclosure_squiretrialthread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(db_index=True, help_text='Unique key for this setting', max_length=100, unique=True)),
                ('setting_value', models.TextField(blank=True, help_text='Value stored as text', null=True)),
                ('setting_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('LIST', 'List'), ('DATETIME', 'DateTime')], default='STRING', help_text='Data type for proper serialization', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Human-readable description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='Category for grouping settings', max_length=50, null=True)),
                ('is_protected', models.BooleanField(default=False, help_text="Protected settings can't be modified via commands")),
            ],
            options={
                'verbose_name': 'Bot Setting',
                'verbose_name_plural': 'Bot Settings',
                'ordering': ['category', 'setting_key'],
                'indexes': [models.Index(fields=['setting_key'], name='orm_models__setting_21757c_idx'), models.Index(fields=['category', 'setting_key'], name='orm_models__categor_5e1a32_idx')],
            },
        ),
    ]
