# Generated by Django 6.0 on 2026-01-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_models', '0004_botsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchasession',
            name='captcha_text',
            field=models.CharField(blank=True, help_text='For text CAPTCHAs', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='captchasession',
            name='math_question',
            field=models.CharField(blank=True, help_text='For math CAPTCHAs', max_length=100, null=True),
        ),
    ]
