# Generated by Django 6.0 on 2026-01-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_models', '0005_captchasession_captcha_text_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsiverification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rsiverification',
            name='discord_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rsiverification',
            name='verification_data',
            field=models.JSONField(default=dict, help_text='Additional verification data'),
        ),
        migrations.AddField(
            model_name='rsiverification',
            name='verification_method',
            field=models.CharField(choices=[('BIO_CODE', 'Bio Code Verification'), ('AUTO', 'Auto Verification'), ('MANUAL', 'Manual Verification')], default='BIO_CODE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='rsiverification',
            index=models.Index(fields=['discord_id', 'verification_status'], name='orm_models__discord_079265_idx'),
        ),
        migrations.AddIndex(
            model_name='rsiverification',
            index=models.Index(fields=['verification_code'], name='orm_models__verific_856700_idx'),
        ),
        migrations.AddIndex(
            model_name='rsiverification',
            index=models.Index(fields=['expires_at'], name='orm_models__expires_2c0289_idx'),
        ),
    ]
