# Generated by Django 6.0 on 2026-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_models', '0006_alter_rsiverification_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('new_issue', 'New Issue Test'), ('update_issue', 'Update Issue Test'), ('resolve_issue', 'Resolve Issue Test'), ('channel_name', 'Channel Name Test'), ('dm_notification', 'DM Notification Test'), ('cleanup', 'Cleanup Test'), ('subscription', 'Subscription Test'), ('all', 'All Tests')], max_length=50)),
                ('discord_user_id', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dev Test Log',
                'verbose_name_plural': 'Dev Test Logs',
                'db_table': 'dev_test_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSIIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('discord_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.TextField()),
                ('affected', models.JSONField(default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('lastmod_at', models.DateTimeField(blank=True, null=True)),
                ('informational', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('severity', models.CharField(max_length=50)),
                ('permalink', models.TextField()),
                ('kind', models.CharField(max_length=50)),
                ('markdown_content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSI Issue',
                'verbose_name_plural': 'RSI Issues',
                'db_table': 'rsi_issues',
            },
        ),
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(default='status_embed', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status Message',
                'verbose_name_plural': 'Status Messages',
                'db_table': 'sc_status_messages',
            },
        ),
        migrations.CreateModel(
            name='StatusDMMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.CharField(max_length=255)),
                ('dm_message_id', models.CharField(max_length=255)),
                ('incident_guid', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_title', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('confirmation', 'Confirmation'), ('update', 'Update'), ('unsubscribe', 'Unsubscribe'), ('test', 'Test')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Status DM Message',
                'verbose_name_plural': 'Status DM Messages',
                'db_table': 'sc_status_dm_messages',
                'indexes': [models.Index(fields=['discord_user_id', 'message_type'], name='sc_status_d_discord_085045_idx'), models.Index(fields=['incident_guid'], name='sc_status_d_inciden_ed03b0_idx'), models.Index(fields=['created_at'], name='sc_status_d_created_ee25e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status Subscription',
                'verbose_name_plural': 'Status Subscriptions',
                'db_table': 'sc_status_subscriptions',
                'constraints': [models.UniqueConstraint(fields=('discord_user_id',), name='unique_user_subscription')],
            },
        ),
    ]
