# Generated by Django 5.2.9 on 2026-01-12 14:40

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orm_models",
            "0007_devtestlog_rsiissue_statusmessage_statusdmmessage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalVoiceBan",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True)),
                ("invoked_at", models.DateTimeField(blank=True, editable=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("REDC", "All Red Channels"),
                            ("ONEC", "A Specific Channel"),
                        ],
                        db_index=True,
                        default="REDC",
                        max_length=4,
                    ),
                ),
                ("kind_specific_metadata", models.JSONField(default=dict)),
                ("history_user_id", models.IntegerField(null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical voice ban",
                "verbose_name_plural": "historical voice bans",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VoiceBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True)),
                ("invoked_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("REDC", "All Red Channels"),
                            ("ONEC", "A Specific Channel"),
                        ],
                        db_index=True,
                        default="REDC",
                        max_length=4,
                    ),
                ),
                ("kind_specific_metadata", models.JSONField(default=dict)),
            ],
        ),
    ]
