# Generated by Django 5.2.9 on 2026-01-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orm_models", "0008_historicalvoiceban_voiceban"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalVoiceBan",
        ),
    ]
