# Generated by Django 6.0 on 2026-01-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_models', '0010_historicalvoiceban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryvoicechannel',
            name='color_role_id',
        ),
        migrations.RemoveField(
            model_name='temporaryvoicechannel',
            name='current_color',
        ),
        migrations.AddField(
            model_name='temporaryvoicechannel',
            name='channel_type',
            field=models.CharField(choices=[('PUBLIC', 'Public Channel'), ('BLUE', 'Blue Team Channel'), ('RED', 'Red Team Channel')], db_index=True, default='PUBLIC', help_text='Type of channel (PUBLIC, BLUE, RED)', max_length=10),
        ),
        migrations.AlterField(
            model_name='temporaryvoicechannel',
            name='parent_channel_id',
            field=models.BigIntegerField(db_index=True, help_text='Parent voice channel ID that triggered creation (PUBLIC, BLUE, or RED parent)'),
        ),
        migrations.AddIndex(
            model_name='temporaryvoicechannel',
            index=models.Index(fields=['channel_type', 'is_active'], name='orm_models__channel_0eaa06_idx'),
        ),
    ]
