# Generated by Django 5.2.9 on 2026-01-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm_models", "0011_remove_temporaryvoicechannel_color_role_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateNotifyThread",
            fields=[
                (
                    "user_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("thread_id", models.BigIntegerField(unique=True)),
            ],
        ),
    ]
