# Generated by Django 6.0 on 2026-01-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_models', '0012_privatenotifythread'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntombedKnight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(max_length=100)),
                ('rank', models.CharField(help_text='Rank at time of entombment', max_length=10)),
                ('entombed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entombed Knight',
                'verbose_name_plural': 'Entombed Knights',
                'ordering': ['-entombed_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('rank_code', models.CharField(max_length=10)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion History',
                'verbose_name_plural': 'Promotion Histories',
                'ordering': ['-promoted_at'],
            },
        ),
    ]
