# Generated by Django 6.0 on 2026-01-21 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_models', '0013_entombedknight_promotionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100)),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('ORGANIC', 'Organic Event'), ('SCHEDULED', 'Scheduled Event'), ('TRAINING', 'Training Session'), ('MEETING', 'Organization Meeting'), ('SOCIAL', 'Social Gathering'), ('OPERATION', 'Military Operation')], max_length=20)),
                ('organizer_id', models.BigIntegerField()),
                ('thread_id', models.BigIntegerField(blank=True, null=True)),
                ('voice_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField()),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('total_participants', models.IntegerField(default=0)),
                ('average_attendance_duration', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-actual_start'],
            },
        ),
        migrations.CreateModel(
            name='VoiceActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('guild_id', models.BigIntegerField(db_index=True)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('TOTAL', 'Total')], default='DAILY', max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('total_talking_seconds', models.IntegerField(default=0)),
                ('unique_channels', models.IntegerField(default=0)),
                ('avg_session_duration', models.IntegerField(default=0)),
                ('avg_talking_percentage', models.FloatField(default=0.0)),
                ('peak_concurrent_users', models.IntegerField(default=0)),
                ('most_active_channel', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'period_type', 'period_start'], name='orm_models__user_id_64068c_idx')],
                'unique_together': {('user_id', 'guild_id', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('guild_id', models.BigIntegerField(db_index=True)),
                ('channel_id', models.BigIntegerField(db_index=True)),
                ('channel_name', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('was_muted', models.BooleanField(default=False)),
                ('was_deafened', models.BooleanField(default=False)),
                ('was_streaming', models.BooleanField(default=False)),
                ('was_video', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('talking_time_seconds', models.IntegerField(default=0, help_text='Time actually talking (not muted/deafened)')),
                ('ended_normally', models.BooleanField(default=True)),
                ('disconnect_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-join_time'],
                'indexes': [models.Index(fields=['user_id', 'join_time'], name='orm_models__user_id_0b56bb_idx'), models.Index(fields=['guild_id', 'channel_id'], name='orm_models__guild_i_255968_idx'), models.Index(fields=['join_time', 'leave_time'], name='orm_models__join_ti_3afbcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Arrived Late'), ('LEFT_EARLY', 'Left Early'), ('EXCUSED', 'Excused Absence'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20)),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('total_talking_seconds', models.IntegerField(default=0)),
                ('was_active_participant', models.BooleanField(default=False)),
                ('verified_by', models.BigIntegerField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='orm_models.eventattendance')),
                ('voice_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm_models.voicesession')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'user_id'], name='orm_models__event_i_95240a_idx'), models.Index(fields=['user_id', 'join_time'], name='orm_models__user_id_bf7339_idx')],
                'unique_together': {('event', 'user_id')},
            },
        ),
    ]
