# Generated by Django 6.0 on 2026-01-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_models', '0014_eventattendance_voiceactivitysummary_voicesession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCrashRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('crash_time', models.DateTimeField()),
                ('recovery_time', models.DateTimeField(blank=True, null=True)),
                ('crash_type', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField()),
                ('active_sessions_lost', models.IntegerField(default=0)),
                ('sessions_recovered', models.IntegerField(default=0)),
                ('recovery_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('bot_version', models.CharField(max_length=50)),
                ('django_version', models.CharField(max_length=50)),
                ('python_version', models.CharField(max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot Crash Recovery',
                'verbose_name_plural': 'Bot Crash Recoveries',
                'ordering': ['-crash_time'],
            },
        ),
        migrations.CreateModel(
            name='VoiceActivityExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('export_type', models.CharField(choices=[('FULL', 'Full Export'), ('INCREMENTAL', 'Incremental Export'), ('BACKUP', 'Backup Export'), ('RECOVERY', 'Recovery Export')], default='BACKUP', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('user_ids', models.JSONField(default=list, help_text='List of user IDs included in export')),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('storage_url', models.URLField(blank=True, max_length=500, null=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Voice Activity Export',
                'verbose_name_plural': 'Voice Activity Exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSessionCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('guild_id', models.BigIntegerField()),
                ('channel_id', models.BigIntegerField()),
                ('channel_name', models.CharField(max_length=200)),
                ('join_time', models.DateTimeField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_deafened', models.BooleanField(default=False)),
                ('is_afk', models.BooleanField(default=False)),
                ('is_streaming', models.BooleanField(default=False)),
                ('talking_start_time', models.DateTimeField(blank=True, null=True)),
                ('talking_paused_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_talking_seconds', models.IntegerField(default=0)),
                ('device_info', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event_checkpoint',
            field=models.JSONField(default=dict, help_text='Checkpoint data for crash recovery'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='is_recovered',
            field=models.BooleanField(default=False, help_text='Event was recovered after restart'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='max_concurrent_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventattendancerecord',
            name='checkpoint_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventattendancerecord',
            name='is_restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventattendancerecord',
            name='participation_score',
            field=models.FloatField(default=0.0, help_text='0-100 score based on talking time and duration'),
        ),
        migrations.AddField(
            model_name='eventattendancerecord',
            name='was_afk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventattendancerecord',
            name='was_deafened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventattendancerecord',
            name='was_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='avg_talking_per_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='consistency_score',
            field=models.FloatField(default=0.0, help_text='0-100 score based on daily participation'),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='excellent_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='fair_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='good_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='inactive_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='most_active_channel_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='mute_avoidance',
            field=models.FloatField(default=0.0, help_text='Percentage of time not muted/deafened'),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='poor_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='restored_sessions',
            field=models.IntegerField(default=0, help_text='Sessions restored after crashes'),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='sessions_lost',
            field=models.IntegerField(default=0, help_text='Sessions lost due to bot restarts'),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='streak_days',
            field=models.IntegerField(default=0, help_text='Consecutive days with voice activity'),
        ),
        migrations.AddField(
            model_name='voiceactivitysummary',
            name='talking_efficiency',
            field=models.FloatField(default=0.0, help_text='Talking time / total time ratio'),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='checkpoint_id',
            field=models.CharField(blank=True, help_text='Checkpoint ID for crash recovery', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='session_quality',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent (>80% talking)'), ('GOOD', 'Good (50-80% talking)'), ('FAIR', 'Fair (20-50% talking)'), ('POOR', 'Poor (<20% talking)'), ('INACTIVE', 'Inactive (muted/deafened/afk)')], default='FAIR', max_length=20),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='session_restored',
            field=models.BooleanField(default=False, help_text='Session was restored from persistence after bot restart'),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='talking_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage of time spent talking'),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='was_afk',
            field=models.BooleanField(default=False, help_text='User was in AFK channel'),
        ),
        migrations.AlterField(
            model_name='eventattendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Arrived Late'), ('LEFT_EARLY', 'Left Early'), ('EXCUSED', 'Excused Absence'), ('ABSENT', 'Absent'), ('ACTIVE', 'Currently Active')], default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='voicesession',
            name='talking_time_seconds',
            field=models.IntegerField(default=0, help_text='Time actually talking (not muted/deafened/afk)'),
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['event_id', 'event_type'], name='orm_models__event_i_2de412_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['organizer_id', 'actual_start'], name='orm_models__organiz_4fadfd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['voice_channel_id'], name='orm_models__voice_c_e4e05a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendancerecord',
            index=models.Index(fields=['checkpoint_id'], name='orm_models__checkpo_81f4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendancerecord',
            index=models.Index(fields=['participation_score'], name='orm_models__partici_b2a729_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceactivitysummary',
            index=models.Index(fields=['guild_id', 'period_type', 'period_end'], name='orm_models__guild_i_1c9c57_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceactivitysummary',
            index=models.Index(fields=['consistency_score'], name='orm_models__consist_807ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['was_afk', 'was_muted', 'was_deafened'], name='orm_models__was_afk_223e93_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['session_quality'], name='orm_models__session_d7a962_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['checkpoint_id'], name='orm_models__checkpo_e86b9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventattendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('total_talking_seconds__gte', 0)), name='attendance_positive_talking'),
        ),
        migrations.AddConstraint(
            model_name='eventattendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('participation_score__gte', 0), ('participation_score__lte', 100)), name='valid_participation_score'),
        ),
        migrations.AddConstraint(
            model_name='voiceactivitysummary',
            constraint=models.CheckConstraint(condition=models.Q(('total_duration_seconds__gte', 0)), name='summary_positive_duration'),
        ),
        migrations.AddConstraint(
            model_name='voiceactivitysummary',
            constraint=models.CheckConstraint(condition=models.Q(('consistency_score__gte', 0), ('consistency_score__lte', 100)), name='valid_consistency_score'),
        ),
        migrations.AddConstraint(
            model_name='voicesession',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gte', 0)), name='positive_duration'),
        ),
        migrations.AddConstraint(
            model_name='voicesession',
            constraint=models.CheckConstraint(condition=models.Q(('talking_time_seconds__gte', 0)), name='positive_talking_time'),
        ),
        migrations.AddConstraint(
            model_name='voicesession',
            constraint=models.CheckConstraint(condition=models.Q(('talking_percentage__gte', 0), ('talking_percentage__lte', 100)), name='valid_talking_percentage'),
        ),
        migrations.AddIndex(
            model_name='botcrashrecovery',
            index=models.Index(fields=['crash_time', 'is_resolved'], name='orm_models__crash_t_d55c75_idx'),
        ),
        migrations.AddIndex(
            model_name='botcrashrecovery',
            index=models.Index(fields=['bot_version'], name='orm_models__bot_ver_905c55_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceactivityexport',
            index=models.Index(fields=['export_id', 'is_completed'], name='orm_models__export__978c06_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceactivityexport',
            index=models.Index(fields=['start_date', 'end_date'], name='orm_models__start_d_109e71_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesessioncheckpoint',
            index=models.Index(fields=['checkpoint_id', 'is_active'], name='orm_models__checkpo_b722cb_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesessioncheckpoint',
            index=models.Index(fields=['user_id', 'is_active'], name='orm_models__user_id_8c0ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesessioncheckpoint',
            index=models.Index(fields=['last_update'], name='orm_models__last_up_3e92c5_idx'),
        ),
    ]
