# Generated by Django 6.0.2 on 2026-02-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm_models", "0015_botcrashrecovery_voiceactivityexport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistinctionLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        help_text="Distinction Level (1-10)", unique=True
                    ),
                ),
                (
                    "nominations_required",
                    models.IntegerField(
                        help_text="Number of nominations required for this level"
                    ),
                ),
                (
                    "role_id",
                    models.BigIntegerField(
                        help_text="Discord Role ID for this distinction level"
                    ),
                ),
                (
                    "role_name",
                    models.CharField(help_text="Discord Role Name", max_length=100),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        default="#0099FF", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "perks",
                    models.JSONField(
                        default=list, help_text="List of perks for this level"
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction Level",
                "verbose_name_plural": "Distinction Levels",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="EventReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True, help_text="ID from source system", max_length=100
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("ORGANIC", "Organic Event System"),
                            ("SCHEDULED", "Scheduled Event System"),
                            ("MANUAL", "Manual Entry"),
                            ("VC_TRACKING", "Voice Channel Tracking"),
                            ("ATTENDANCE", "Attendance System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_name", models.CharField(max_length=200)),
                ("event_description", models.TextField(blank=True, null=True)),
                ("event_date", models.DateTimeField()),
                ("organizer_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "organizer_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "participant_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of Discord user IDs who participated",
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event Reference",
                "verbose_name_plural": "Event References",
            },
        ),
        migrations.CreateModel(
            name="HangarStatusMessage",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=1,
                        help_text="Fixed ID for single record system",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discord Message ID of the status embed",
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time the message was updated"
                    ),
                ),
                (
                    "last_phase_change",
                    models.DateTimeField(
                        blank=True, help_text="Last time phase changed", null=True
                    ),
                ),
                (
                    "last_light_change",
                    models.DateTimeField(
                        blank=True, help_text="Last time lights changed", null=True
                    ),
                ),
                (
                    "notification_count",
                    models.IntegerField(
                        default=0, help_text="Number of notifications sent"
                    ),
                ),
                ("last_website_sync", models.DateTimeField(blank=True, null=True)),
                ("website_sync_attempts", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Hangar Status Message",
                "verbose_name_plural": "Hangar Status Messages",
                "db_table": "hangar_status_messages",
            },
        ),
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nominee_id",
                    models.BigIntegerField(
                        db_index=True, help_text="Discord ID of the nominated user"
                    ),
                ),
                (
                    "nominator_id",
                    models.BigIntegerField(
                        db_index=True, help_text="Discord ID of the nominator"
                    ),
                ),
                (
                    "nominee_username",
                    models.CharField(
                        help_text="Nominee's username at time of nomination",
                        max_length=100,
                    ),
                ),
                (
                    "nominator_username",
                    models.CharField(help_text="Nominator's username", max_length=100),
                ),
                (
                    "event_date",
                    models.CharField(help_text="Date or event name", max_length=200),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional: ID of related event from event system",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "event_source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manually entered"),
                            ("ORGANIC", "Organic Event System"),
                            ("SCHEDULED", "Scheduled Event"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for nomination")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved - Nomination Awarded"),
                            ("RECOGNIZED", "Approved - Recognition Granted"),
                            ("DENIED", "Denied"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "processed_by_id",
                    models.BigIntegerField(
                        blank=True, help_text="ID of staff who processed", null=True
                    ),
                ),
                (
                    "processed_by_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "denial_reason",
                    models.TextField(
                        blank=True, help_text="Reason for denial if denied", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flags",
                    models.JSONField(default=dict, help_text="Additional metadata"),
                ),
            ],
            options={
                "verbose_name": "Nomination",
                "verbose_name_plural": "Nominations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserDistinction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True, unique=True)),
                ("current_level", models.IntegerField(default=0)),
                ("total_nominations", models.IntegerField(default=0)),
                ("total_recognitions", models.IntegerField(default=0)),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0, help_text="Consecutive months with nominations"
                    ),
                ),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_nomination_date", models.DateTimeField(blank=True, null=True)),
                (
                    "nomination_rate",
                    models.FloatField(default=0.0, help_text="Nominations per month"),
                ),
                (
                    "approval_rate",
                    models.FloatField(
                        default=0.0, help_text="Percentage of nominations approved"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_level_up", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "User Distinction",
                "verbose_name_plural": "User Distinctions",
            },
        ),
        migrations.RenameIndex(
            model_name="botcrashrecovery",
            new_name="orm_models__crash_t_677afc_idx",
            old_name="orm_models__crash_t_d55c75_idx",
        ),
        migrations.RenameIndex(
            model_name="botcrashrecovery",
            new_name="orm_models__bot_ver_0bb4fc_idx",
            old_name="orm_models__bot_ver_905c55_idx",
        ),
        migrations.RenameIndex(
            model_name="botsettings",
            new_name="orm_models__setting_9a239e_idx",
            old_name="orm_models__setting_21757c_idx",
        ),
        migrations.RenameIndex(
            model_name="botsettings",
            new_name="orm_models__categor_9ce4a7_idx",
            old_name="orm_models__categor_5e1a32_idx",
        ),
        migrations.RenameIndex(
            model_name="captchasession",
            new_name="orm_models__discord_2ff79c_idx",
            old_name="orm_models__discord_d7c7f6_idx",
        ),
        migrations.RenameIndex(
            model_name="captchasession",
            new_name="orm_models__expires_c38132_idx",
            old_name="orm_models__expires_c7397f_idx",
        ),
        migrations.RenameIndex(
            model_name="eventattendance",
            new_name="orm_models__event_i_1c5b8e_idx",
            old_name="orm_models__event_i_2de412_idx",
        ),
        migrations.RenameIndex(
            model_name="eventattendance",
            new_name="orm_models__organiz_10b6be_idx",
            old_name="orm_models__organiz_4fadfd_idx",
        ),
        migrations.RenameIndex(
            model_name="eventattendance",
            new_name="orm_models__voice_c_36f18f_idx",
            old_name="orm_models__voice_c_e4e05a_idx",
        ),
        migrations.RenameIndex(
            model_name="eventattendancerecord",
            new_name="orm_models__event_i_c7c5c7_idx",
            old_name="orm_models__event_i_95240a_idx",
        ),
        migrations.RenameIndex(
            model_name="eventattendancerecord",
            new_name="orm_models__user_id_7d1199_idx",
            old_name="orm_models__user_id_bf7339_idx",
        ),
        migrations.RenameIndex(
            model_name="eventattendancerecord",
            new_name="orm_models__checkpo_6d2c92_idx",
            old_name="orm_models__checkpo_81f4f6_idx",
        ),
        migrations.RenameIndex(
            model_name="eventattendancerecord",
            new_name="orm_models__partici_e28471_idx",
            old_name="orm_models__partici_b2a729_idx",
        ),
        migrations.RenameIndex(
            model_name="membershipapplication",
            new_name="orm_models__applica_572c26_idx",
            old_name="orm_models__applica_c342e8_idx",
        ),
        migrations.RenameIndex(
            model_name="membershipapplication",
            new_name="orm_models__status_79dcf5_idx",
            old_name="orm_models__status_96cc48_idx",
        ),
        migrations.RenameIndex(
            model_name="membershipapplication",
            new_name="orm_models__rsi_ver_58e034_idx",
            old_name="orm_models__rsi_ver_bdc90b_idx",
        ),
        migrations.RenameIndex(
            model_name="rsiverification",
            new_name="orm_models__discord_db5dfe_idx",
            old_name="orm_models__discord_079265_idx",
        ),
        migrations.RenameIndex(
            model_name="rsiverification",
            new_name="orm_models__verific_b3555f_idx",
            old_name="orm_models__verific_856700_idx",
        ),
        migrations.RenameIndex(
            model_name="rsiverification",
            new_name="orm_models__expires_4e18c3_idx",
            old_name="orm_models__expires_2c0289_idx",
        ),
        migrations.RenameIndex(
            model_name="temporaryvoicechannel",
            new_name="orm_models__guild_i_f408f1_idx",
            old_name="orm_models__guild_i_683e79_idx",
        ),
        migrations.RenameIndex(
            model_name="temporaryvoicechannel",
            new_name="orm_models__creator_5a2027_idx",
            old_name="orm_models__creator_6c88ec_idx",
        ),
        migrations.RenameIndex(
            model_name="temporaryvoicechannel",
            new_name="orm_models__parent__3fe395_idx",
            old_name="orm_models__parent__3bd712_idx",
        ),
        migrations.RenameIndex(
            model_name="temporaryvoicechannel",
            new_name="orm_models__channel_2ee82d_idx",
            old_name="orm_models__channel_0eaa06_idx",
        ),
        migrations.RenameIndex(
            model_name="userjoinrecord",
            new_name="orm_models__discord_f79d3c_idx",
            old_name="orm_models__discord_02dc2d_idx",
        ),
        migrations.RenameIndex(
            model_name="userjoinrecord",
            new_name="orm_models__discord_dc7beb_idx",
            old_name="orm_models__discord_8c6311_idx",
        ),
        migrations.RenameIndex(
            model_name="userjoinrecord",
            new_name="orm_models__joined__5998e6_idx",
            old_name="orm_models__joined__65d917_idx",
        ),
        migrations.RenameIndex(
            model_name="userjoinrecord",
            new_name="orm_models__left_at_15f55c_idx",
            old_name="orm_models__left_at_206e2e_idx",
        ),
        migrations.RenameIndex(
            model_name="userjoinrecord",
            new_name="orm_models__last_se_885d6a_idx",
            old_name="orm_models__last_se_b94012_idx",
        ),
        migrations.RenameIndex(
            model_name="userjoinrecord",
            new_name="orm_models__usernam_528322_idx",
            old_name="orm_models__usernam_a50c42_idx",
        ),
        migrations.RenameIndex(
            model_name="userjoinrecord",
            new_name="orm_models__global__297fe7_idx",
            old_name="orm_models__global__aed958_idx",
        ),
        migrations.RenameIndex(
            model_name="userjoinrecord",
            new_name="orm_models__join_co_73a072_idx",
            old_name="orm_models__join_co_63a95f_idx",
        ),
        migrations.RenameIndex(
            model_name="voiceactivityexport",
            new_name="orm_models__export__5c6e04_idx",
            old_name="orm_models__export__978c06_idx",
        ),
        migrations.RenameIndex(
            model_name="voiceactivityexport",
            new_name="orm_models__start_d_5eb7a7_idx",
            old_name="orm_models__start_d_109e71_idx",
        ),
        migrations.RenameIndex(
            model_name="voiceactivitysummary",
            new_name="orm_models__user_id_42a7f6_idx",
            old_name="orm_models__user_id_64068c_idx",
        ),
        migrations.RenameIndex(
            model_name="voiceactivitysummary",
            new_name="orm_models__guild_i_bb9739_idx",
            old_name="orm_models__guild_i_1c9c57_idx",
        ),
        migrations.RenameIndex(
            model_name="voiceactivitysummary",
            new_name="orm_models__consist_3ec726_idx",
            old_name="orm_models__consist_807ccb_idx",
        ),
        migrations.RenameIndex(
            model_name="voicesession",
            new_name="orm_models__user_id_b5047f_idx",
            old_name="orm_models__user_id_0b56bb_idx",
        ),
        migrations.RenameIndex(
            model_name="voicesession",
            new_name="orm_models__guild_i_76fb10_idx",
            old_name="orm_models__guild_i_255968_idx",
        ),
        migrations.RenameIndex(
            model_name="voicesession",
            new_name="orm_models__join_ti_30ea3e_idx",
            old_name="orm_models__join_ti_3afbcc_idx",
        ),
        migrations.RenameIndex(
            model_name="voicesession",
            new_name="orm_models__was_afk_f9a5cb_idx",
            old_name="orm_models__was_afk_223e93_idx",
        ),
        migrations.RenameIndex(
            model_name="voicesession",
            new_name="orm_models__session_592e15_idx",
            old_name="orm_models__session_d7a962_idx",
        ),
        migrations.RenameIndex(
            model_name="voicesession",
            new_name="orm_models__checkpo_c408f1_idx",
            old_name="orm_models__checkpo_e86b9b_idx",
        ),
        migrations.RenameIndex(
            model_name="voicesessioncheckpoint",
            new_name="orm_models__checkpo_b055ff_idx",
            old_name="orm_models__checkpo_b722cb_idx",
        ),
        migrations.RenameIndex(
            model_name="voicesessioncheckpoint",
            new_name="orm_models__user_id_c9b21e_idx",
            old_name="orm_models__user_id_8c0ca1_idx",
        ),
        migrations.RenameIndex(
            model_name="voicesessioncheckpoint",
            new_name="orm_models__last_up_274786_idx",
            old_name="orm_models__last_up_3e92c5_idx",
        ),
        migrations.AddConstraint(
            model_name="distinctionlevel",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__gte", 1), ("level__lte", 10)),
                name="distinction_level_range",
            ),
        ),
        migrations.AddIndex(
            model_name="eventreference",
            index=models.Index(
                fields=["event_id", "source_system"],
                name="orm_models__event_i_5c8bbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventreference",
            index=models.Index(
                fields=["event_date"], name="orm_models__event_d_f99489_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventreference",
            index=models.Index(
                fields=["organizer_id"], name="orm_models__organiz_1c0655_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventreference",
            unique_together={("event_id", "source_system")},
        ),
        migrations.AddConstraint(
            model_name="hangarstatusmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", 1)), name="single_hangar_status_record"
            ),
        ),
        migrations.AddIndex(
            model_name="nomination",
            index=models.Index(
                fields=["nominee_id", "status"], name="orm_models__nominee_c5b366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nomination",
            index=models.Index(
                fields=["nominator_id"], name="orm_models__nominat_8acc14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nomination",
            index=models.Index(
                fields=["status", "created_at"], name="orm_models__status_bc82b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nomination",
            index=models.Index(
                fields=["event_id"], name="orm_models__event_i_d3c0fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdistinction",
            index=models.Index(
                fields=["user_id", "current_level"],
                name="orm_models__user_id_9c1ad1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userdistinction",
            index=models.Index(
                fields=["current_level"], name="orm_models__current_ad5320_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdistinction",
            index=models.Index(
                fields=["total_nominations"], name="orm_models__total_n_7115ca_idx"
            ),
        ),
    ]
