# Generated by Django 6.0.2 on 2026-03-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "orm_models",
            "0017_rename_orm_models__crash_t_677afc_idx_orm_models__crash_t_d55c75_idx_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="SquireTrialThread",
        ),
    ]
