# Generated by Django 6.0 on 2026-03-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_models', '0018_delete_squiretrialthread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevTestLog',
        ),
        migrations.RemoveConstraint(
            model_name='hangarstatusmessage',
            name='single_hangar_status_record',
        ),
        migrations.DeleteModel(
            name='HangarStatusMessage',
        ),
        migrations.DeleteModel(
            name='RSIIssue',
        ),
        migrations.RemoveIndex(
            model_name='statusdmmessage',
            name='sc_status_d_discord_085045_idx',
        ),
        migrations.RemoveIndex(
            model_name='statusdmmessage',
            name='sc_status_d_inciden_ed03b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='statusdmmessage',
            name='sc_status_d_created_ee25e9_idx',
        ),
        migrations.DeleteModel(
            name='StatusDMMessage',
        ),
        migrations.DeleteModel(
            name='StatusMessage',
        ),
        migrations.RemoveConstraint(
            model_name='statussubscription',
            name='unique_user_subscription',
        ),
        migrations.DeleteModel(
            name='StatusSubscription',
        ),
    ]
