# Generated by Django 6.0 on 2026-04-29 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot_tracker', '0003_slugs_uuids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallootitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical loot item', 'verbose_name_plural': 'historical loot items'},
        ),
        migrations.AlterModelOptions(
            name='historicallootrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical loot request', 'verbose_name_plural': 'historical loot requests'},
        ),
        migrations.AlterModelOptions(
            name='historicallootstock',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Loot Stock Level', 'verbose_name_plural': 'historical Loot Stock Levels'},
        ),
        migrations.AlterModelOptions(
            name='historicalmeritrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical merit request', 'verbose_name_plural': 'historical merit requests'},
        ),
        migrations.AlterModelOptions(
            name='historicalstockitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical stock item', 'verbose_name_plural': 'historical stock items'},
        ),
        migrations.AlterModelOptions(
            name='historicalstockunit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical stock unit', 'verbose_name_plural': 'historical stock units'},
        ),
        migrations.AlterModelOptions(
            name='historicaltrackedcraftedweapon',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tracked crafted weapon', 'verbose_name_plural': 'historical tracked crafted weapons'},
        ),
        migrations.AlterModelOptions(
            name='historicaltrackedcraftedweaponstate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tracked crafted weapon state', 'verbose_name_plural': 'historical tracked crafted weapon states'},
        ),
        migrations.AddField(
            model_name='historicallootitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='historicallootrequest',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicallootstock',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmeritrequest',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicalstockitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='historicalstockunit',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicallootitem',
            name='category',
            field=models.CharField(choices=[('CURRENCY', 'Currency (aUEC/Merits)'), ('WIKELO_CURRENCY', 'Wikelo Currencies'), ('WIKELO_MATERIAL', 'Wikelo Materials'), ('MONSTER_PART', 'Monster Parts'), ('MILITARY', 'Military Items'), ('COMPONENT', 'Wikelo Components'), ('WEAPON', 'Weapons'), ('LEGACY', 'Legacy Loot'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicallootitem',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicallootitem',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicallootitem',
            name='location',
            field=models.CharField(choices=[('STANTON', 'Stanton'), ('PYRO', 'Pyro'), ('NYX', 'Nyx'), ('UNIVERSAL', 'Universal (no location)')], db_index=True, default='STANTON', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicallootitem',
            name='location_agnostic',
            field=models.BooleanField(default=False, help_text='No location asked on requests (e.g. aUEC, Merits).'),
        ),
        migrations.AlterField(
            model_name='historicallootitem',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='historicallootrequest',
            name='direction',
            field=models.CharField(choices=[('INPUT', 'Input (deposit)'), ('WITHDRAW', 'Withdraw')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicallootrequest',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicallootrequest',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicallootrequest',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loot_tracker.lootitem'),
        ),
        migrations.AlterField(
            model_name='historicallootrequest',
            name='location',
            field=models.CharField(blank=True, choices=[('STANTON', 'Stanton'), ('PYRO', 'Pyro'), ('NYX', 'Nyx'), ('UNIVERSAL', 'Universal (no location)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicallootrequest',
            name='requester',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicallootrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicallootrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicallootstock',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicallootstock',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicallootstock',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loot_tracker.lootitem'),
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='kind',
            field=models.CharField(choices=[('MONEY', 'aUEC Payout'), ('MERIT', 'Merit Award')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('DENIED', 'Denied')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalstockitem',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalstockitem',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalstockitem',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalstockunit',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalstockunit',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalstockunit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('RETURNED', 'Returned'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], db_index=True, default='AVAILABLE', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicaltrackedcraftedweapon',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaltrackedcraftedweapon',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicaltrackedcraftedweaponstate',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaltrackedcraftedweaponstate',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicaltrackedcraftedweaponstate',
            name='status',
            field=models.CharField(choices=[('USED', 'Actively in Use'), ('HELD_K', 'Available for Knights'), ('HELD_O', 'Available for Org'), ('LOST_CIG', 'Lost Other'), ('LOST_COMBAT', 'Lost in Combat'), ('EXTERNAL', 'Not under Org control'), ('AWAIT_RET', 'Awaiting Return')], db_index=True, default='EXTERNAL', max_length=14),
        ),
        migrations.AlterField(
            model_name='lootitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lootitem',
            name='location_agnostic',
            field=models.BooleanField(default=False, help_text='No location asked on requests (e.g. aUEC, Merits).'),
        ),
        migrations.AlterField(
            model_name='lootrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lootrequest',
            name='location',
            field=models.CharField(blank=True, choices=[('STANTON', 'Stanton'), ('PYRO', 'Pyro'), ('NYX', 'Nyx'), ('UNIVERSAL', 'Universal (no location)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lootstatusmessage',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lootstock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meritrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trackedcraftedrequests',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trackedcraftedweapon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trackedcraftedweaponstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
