# Generated by Django 6.0.5 on 2026-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot_tracker', '0005_stockitem_subcategory_stats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lootitem',
            options={'default_permissions': (), 'ordering': ['category', 'name'], 'permissions': [('manage_loot', 'QM: Can manage loot items, stock levels, and requests'), ('submit_loot_request', 'Can submit loot input/withdraw requests'), ('view_loot', 'Can view loot inventory'), ('manage_stock', 'Can add, edit, and remove stock items and units'), ('assign_stock', 'Can assign stock units to members'), ('view_stock', 'Can view the stock inventory'), ('submit_merit_request', 'Can submit merit/money requests'), ('review_merit_request', 'Can approve or deny merit/money requests'), ('fulfill_merit_request', 'Can mark merit/money requests as fulfilled'), ('view_merit_requests', 'Can view all merit/money requests'), ('can_submit_new_weapon', 'Can submit new crafted weapon'), ('can_see_weapon_listing', 'Can see weapon listing'), ('can_request_held_limited', 'Can request weapon held for Knights'), ('can_request_held_orgwide', 'Can request weapon held for Org'), ('can_approve_requests', 'Can approve weapon requests'), ('can_discord_manage_state', 'Can manage weapon state in Discord')]},
        ),
        migrations.AddField(
            model_name='historicalstockitem',
            name='sc_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Star Citizen item metadata (manufacturer, class, item_type, attachments, …)'),
        ),
        migrations.AddField(
            model_name='historicalstockitem',
            name='tracking_mode',
            field=models.CharField(choices=[('UNIT', 'Individual Unit'), ('BULK_SCU', 'Bulk / SCU Volume'), ('CRAFTED', 'Crafted Item')], db_index=True, default='UNIT', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalstockunit',
            name='craft_state',
            field=models.CharField(blank=True, choices=[('HELD_K', 'Available for Knights'), ('HELD_O', 'Available for Org'), ('IN_USE', 'Actively in Use'), ('AWAIT_RET', 'Awaiting Return'), ('EXTERNAL', 'Not under Org control'), ('LOST_COMBAT', 'Lost in Combat'), ('LOST_OTHER', 'Lost / Other')], db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalstockunit',
            name='sc_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Per-unit SC metadata (serial, source location, scan date, …)'),
        ),
        migrations.AddField(
            model_name='historicalstockunit',
            name='scu_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SCU volume for bulk/ore items', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sc_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Star Citizen item metadata (manufacturer, class, item_type, attachments, …)'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='tracking_mode',
            field=models.CharField(choices=[('UNIT', 'Individual Unit'), ('BULK_SCU', 'Bulk / SCU Volume'), ('CRAFTED', 'Crafted Item')], db_index=True, default='UNIT', max_length=10),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='craft_state',
            field=models.CharField(blank=True, choices=[('HELD_K', 'Available for Knights'), ('HELD_O', 'Available for Org'), ('IN_USE', 'Actively in Use'), ('AWAIT_RET', 'Awaiting Return'), ('EXTERNAL', 'Not under Org control'), ('LOST_COMBAT', 'Lost in Combat'), ('LOST_OTHER', 'Lost / Other')], db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='sc_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Per-unit SC metadata (serial, source location, scan date, …)'),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='scu_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SCU volume for bulk/ore items', max_digits=10, null=True),
        ),
    ]
