# Generated by Django 6.0.5 on 2026-05-11 23:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot_tracker', '0006_alter_lootitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('FPS_ARMOR', 'FPS Armor'), ('FPS_WEAPON', 'FPS Weapon'), ('SHIP_WEAPON', 'Ship Weapon'), ('SHIP', 'Ship'), ('COMPONENT', 'Ship Component'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blueprints', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.OneToOneField(help_text='The StockItem this blueprint produces.', on_delete=django.db.models.deletion.CASCADE, related_name='blueprint', to='loot_tracker.stockitem')),
            ],
            options={
                'ordering': ['item_type', 'stock_item__name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CraftConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_label', models.CharField(help_text='Must match constraint_group on linked CraftMaterial rows', max_length=10)),
                ('combined_total', models.PositiveIntegerField(help_text='Combined temperature total required across grouped materials')),
                ('note', models.TextField(blank=True, help_text='Human-readable explanation of the constraint')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='loot_tracker.craftblueprint')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CraftMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('min_temp', models.PositiveIntegerField(help_text='Minimum refining temperature')),
                ('temp_is_floor', models.BooleanField(default=True, help_text='Checked = minimum threshold (900+). Unchecked = exact temperature.')),
                ('yield_min', models.DecimalField(decimal_places=4, help_text='Minimum yield fraction (e.g. 0.05 for 5%)', max_digits=6)),
                ('yield_max', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum yield fraction. Leave blank if same as minimum.', max_digits=6, null=True)),
                ('constraint_group', models.CharField(blank=True, help_text="Label linking materials sharing a combined constraint (e.g. '*'). Must match a CraftConstraint group_label.", max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='loot_tracker.craftblueprint')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HistoricalCraftBlueprint',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('FPS_ARMOR', 'FPS Armor'), ('FPS_WEAPON', 'FPS Weapon'), ('SHIP_WEAPON', 'Ship Weapon'), ('SHIP', 'Ship'), ('COMPONENT', 'Ship Component'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(blank=True, db_constraint=False, help_text='The StockItem this blueprint produces.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loot_tracker.stockitem')),
            ],
            options={
                'verbose_name': 'historical craft blueprint',
                'verbose_name_plural': 'historical craft blueprints',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
