# Generated by Django 6.0.2 on 2026-03-08 12:11

import app.discordwebcms.models
import app.main.util.db
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discord_thread_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID of the Discord Forum Thread",
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="discordwebcms.tag"
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text (Markdown)"),
                            ("VIDEO", "Video URL"),
                            ("IMAGE", "Image Upload"),
                            ("FILE", "File Upload"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "discord_message_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID of the Discord Message inside the thread",
                        null=True,
                    ),
                ),
                (
                    "discord_message_attachment_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ID of the Discord Message Attachment",
                        null=True,
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True, help_text="Supports Markdown", null=True
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cms_post_images/",
                        validators=[app.discordwebcms.models.validate_file_size],
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cms_post_files/",
                        validators=[app.discordwebcms.models.validate_file_size],
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="discordwebcms.post",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("file_upload__isnull", True),
                                ("image_file__isnull", True),
                                ("text_content__isnull", False),
                                ("video_url__isnull", True),
                            ),
                            models.Q(
                                ("file_upload__isnull", True),
                                ("image_file__isnull", True),
                                ("text_content__isnull", True),
                                ("video_url__isnull", False),
                            ),
                            models.Q(
                                ("file_upload__isnull", True),
                                ("image_file__isnull", False),
                                ("text_content__isnull", True),
                                ("video_url__isnull", True),
                            ),
                            models.Q(
                                ("file_upload__isnull", False),
                                ("image_file__isnull", True),
                                ("text_content__isnull", True),
                                ("video_url__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="one_content_type_only",
                    )
                ],
            },
            bases=(app.main.util.db.OriginalStateMixin, models.Model),
        ),
    ]
