# Generated by Django 6.0.2 on 2026-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordwebcms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entry",
            name="one_content_type_only",
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("text_content__in", ["", None]), _negated=True),
                        ("video_url__in", ["", None]),
                        ("image_file__in", ["", None]),
                        ("file_upload__in", ["", None]),
                    ),
                    models.Q(
                        ("text_content__in", ["", None]),
                        models.Q(("video_url__in", ["", None]), _negated=True),
                        ("image_file__in", ["", None]),
                        ("file_upload__in", ["", None]),
                    ),
                    models.Q(
                        ("text_content__in", ["", None]),
                        ("video_url__in", ["", None]),
                        models.Q(("image_file__in", ["", None]), _negated=True),
                        ("file_upload__in", ["", None]),
                    ),
                    models.Q(
                        ("text_content__in", ["", None]),
                        ("video_url__in", ["", None]),
                        ("image_file__in", ["", None]),
                        models.Q(("file_upload__in", ["", None]), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="one_content_type_only",
            ),
        ),
    ]
