# Generated by Django 6.0 on 2026-04-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordwebcms', '0002_remove_entry_one_content_type_only_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('order',), 'permissions': [('view_staff_post', 'Can view staff-only knowledge base posts')]},
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public (all members)'), ('STAFF', 'Staff only')], db_index=True, default='PUBLIC', help_text='PUBLIC = all members via /kbsearch; STAFF = only users with discordwebcms.view_staff_post', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
