# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordwebcms', '0003_alter_post_options_post_visibility_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'default_permissions': (), 'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': [('view_staff_post', 'Can view staff-only knowledge base posts')]},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_permissions': (), 'ordering': ('order',)},
        ),
    ]
