# Generated by Django 6.0 on 2026-04-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discorduser',
            options={'permissions': [('can_link_discord_accounts', 'Can link Discord accounts to site accounts via bot command')]},
        ),
    ]
