# Generated by Django 6.0.2 on 2026-02-09 07:14

import app.main.util.db
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordRole",
            fields=[
                ("role_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("discord_order", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ("discord_order",),
            },
            bases=(app.main.util.db.DBAwareModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GroupDiscordRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="org.discordrole",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
            ],
            bases=(app.main.util.db.DBAwareModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="discordrole",
            name="permission_groups",
            field=models.ManyToManyField(
                related_name="discord_roles",
                through="org.GroupDiscordRole",
                to="auth.group",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupdiscordrole",
            constraint=models.UniqueConstraint(
                fields=("discord_role", "group"), name="ut_org_groupdiscordrole_1"
            ),
        ),
    ]
