# Generated by Django 6.0.2 on 2026-03-04 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordauth", "0001_initial"),
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupdiscordrole",
            name="id",
            field=models.BigIntegerField(
                help_text="Discord Message ID", primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="DiscordUserGuildEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("user_join", "User Join"),
                            ("user_leave", "User Leave"),
                            ("user_delete", "User Update"),
                            ("user_update", "User Update"),
                            ("user_new", "User Newly Detected"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "discorduser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guildevents",
                        to="discordauth.discorduser",
                    ),
                ),
            ],
        ),
    ]
