# Generated by Django 6.0.2 on 2026-03-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0002_alter_groupdiscordrole_id_discorduserguildevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discordrole",
            options={"ordering": ("-discord_order",)},
        ),
        migrations.AlterField(
            model_name="groupdiscordrole",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
