# Generated by Django 6.0 on 2026-04-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_discrole_can_manage_discord_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordrole',
            options={'ordering': ('-discord_order',), 'permissions': [('can_manage_discord_members', 'Can manage Discord members via bot commands')]},
        ),
    ]
