# Generated by Django 6.0 on 2026-04-23 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_alter_discordrole_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Shown to leaders when picking a template.')),
                ('body', models.TextField(help_text='Message body. Available tokens: {author} {author_name} {discipline} {date} {custom_1} … {custom_5}')),
                ('target_channel_id', models.BigIntegerField(blank=True, help_text='Discord channel snowflake. Leave blank to use the OrgPostDefaultChannelID preference.', null=True)),
                ('ping_discipline', models.BooleanField(default=False, help_text="Mention the discipline's Discord role when posting.")),
                ('requires_approval', models.BooleanField(default=True, help_text='When ON, a leader approval is required before the post is sent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_post_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('use_org_post_template', 'Can draft and submit org posts'), ('approve_org_post', 'Can approve and send org post requests'), ('manage_org_post_template', 'Can create and edit org post templates')],
            },
        ),
        migrations.CreateModel(
            name='OrgPostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Sent'), ('DENIED', 'Denied')], db_index=True, default='PENDING', max_length=10)),
                ('rendered_body', models.TextField()),
                ('discipline_name', models.CharField(blank=True, default='', max_length=100)),
                ('discipline_role_id', models.BigIntegerField(blank=True, null=True)),
                ('custom_1', models.CharField(blank=True, default='', max_length=500)),
                ('custom_2', models.CharField(blank=True, default='', max_length=500)),
                ('custom_3', models.CharField(blank=True, default='', max_length=500)),
                ('custom_4', models.CharField(blank=True, default='', max_length=500)),
                ('custom_5', models.CharField(blank=True, default='', max_length=500)),
                ('denial_reason', models.TextField(blank=True, default='')),
                ('approval_message_id', models.BigIntegerField(blank=True, null=True)),
                ('sent_message_id', models.BigIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_org_posts', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_post_requests', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='org.orgposttemplate')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
