# Generated by Django 6.0 on 2026-04-24 01:21

import app.main.util.db
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_orgposttemplate_orgpostrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPingPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(unique=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='orgpostrequest',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='If set, the post will be sent at this UTC time (after approval).', null=True),
        ),
        migrations.CreateModel(
            name='ActivityPingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name in the portal button/embed.', max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('emoji', models.CharField(blank=True, default='', help_text='Emoji shown next to label (unicode or :name:).', max_length=32)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive roles are hidden from the portal.')),
                ('discord_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_ping_role', to='org.discordrole')),
            ],
            options={
                'ordering': ['display_order', 'label'],
                'permissions': [('manage_activity_ping_roles', 'Can manage activity ping roles')],
            },
            bases=(app.main.util.db.DBAwareModelMixin, models.Model),
        ),
    ]
