# Generated by Django 6.0 on 2026-04-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_activitypingportal_orgpostrequest_scheduled_for_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitypingrole',
            options={'ordering': ['category', 'display_order', 'label'], 'permissions': [('manage_activity_ping_roles', 'Can manage activity ping roles')]},
        ),
        migrations.AddField(
            model_name='activitypingrole',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='Discipline', help_text='Section heading in the portal embed (e.g. "Discipline" or "Other Roles").', max_length=80),
        ),
    ]
