# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_alter_activitypingrole_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitypingportal',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='activitypingrole',
            options={'default_permissions': (), 'ordering': ['category', 'display_order', 'label'], 'permissions': [('manage_activity_ping_roles', 'Can manage activity ping roles')]},
        ),
        migrations.AlterModelOptions(
            name='discordrole',
            options={'default_permissions': (), 'ordering': ('-discord_order',), 'permissions': [('can_manage_discord_members', 'Can manage Discord members via bot commands')]},
        ),
        migrations.AlterModelOptions(
            name='discorduserguildevent',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='groupdiscordrole',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='orgplayernote',
            options={'default_permissions': (), 'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='orgpostrequest',
            options={'default_permissions': (), 'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='orgposttemplate',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('use_org_post_template', 'Can draft and submit org posts'), ('approve_org_post', 'Can approve and send org post requests'), ('manage_org_post_template', 'Can create and edit org post templates')]},
        ),
    ]
