# Generated by Django 6.0 on 2026-04-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_privatenotifythread'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='privatenotifythread',
            table=None,
        ),
    ]
