# Generated by Django 6.0 on 2026-04-29 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0015_alter_privatenotifythread_table'),
        ('unifieduser', '0007_alter_displaynamesearchcache_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypingrole',
            name='min_rank',
            field=models.ForeignKey(blank=True, help_text='Minimum OrgRank required to self-assign. Leave blank for no restriction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='unifieduser.orgrank'),
        ),
    ]
