# Generated by Django 6.0.5 on 2026-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0017_remove_stale_dispatch_scheduled_org_posts_beat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnounceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('SENT', 'Sent Direct')], db_index=True, max_length=10)),
                ('submitter_id', models.BigIntegerField(help_text='Discord user ID of the submitter')),
                ('reviewer_id', models.BigIntegerField(blank=True, help_text='Discord user ID of the approver/denier', null=True)),
                ('audience', models.CharField(blank=True, max_length=120)),
                ('body_preview', models.TextField(blank=True, help_text='First 500 chars of announcement body')),
                ('denial_reason', models.TextField(blank=True)),
                ('target_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announce Audit Log',
                'verbose_name_plural': 'Announce Audit Logs',
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
    ]
