# Generated by Django 6.0.2 on 2026-02-09 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linked_module_class_path",
                    models.CharField(max_length=512, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["linked_module_class_path"],
                        name="preferences_gs_lmcp_vpo",
                        opclasses=["varchar_pattern_ops"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GlobalSettingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField()),
                (
                    "for_setting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="preferences.globalsetting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linked_module_class_path",
                    models.CharField(max_length=512, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["linked_module_class_path"],
                        name="preferences_us_lmcp_vpo",
                        opclasses=["varchar_pattern_ops"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSettingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField()),
                (
                    "for_setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="preferences.usersetting",
                    ),
                ),
                (
                    "for_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("for_setting", "for_user"),
                        name="ut_preferences_usersettingdata_1",
                    )
                ],
            },
        ),
    ]
