# Generated by Django 6.0 on 2026-04-25 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockassignment_options_and_more'),
        ('merits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmeritrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical merit request', 'verbose_name_plural': 'historical merit requests'},
        ),
        migrations.AddField(
            model_name='historicalmeritrequest',
            name='during_event',
            field=models.BooleanField(blank=True, help_text='True=Yes, False=No, None=not applicable', null=True),
        ),
        migrations.AddField(
            model_name='historicalmeritrequest',
            name='purchase_for',
            field=models.CharField(blank=True, help_text='Ship or item the aUEC is being used for', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalmeritrequest',
            name='rsi_handle',
            field=models.CharField(blank=True, help_text='RSI handle of the requester', max_length=60),
        ),
        migrations.AddField(
            model_name='meritrequest',
            name='during_event',
            field=models.BooleanField(blank=True, help_text='True=Yes, False=No, None=not applicable', null=True),
        ),
        migrations.AddField(
            model_name='meritrequest',
            name='purchase_for',
            field=models.CharField(blank=True, help_text='Ship or item the aUEC is being used for', max_length=200),
        ),
        migrations.AddField(
            model_name='meritrequest',
            name='rsi_handle',
            field=models.CharField(blank=True, help_text='RSI handle of the requester', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='aUEC amount (MONEY) or merit points (MERIT). 0 = TBD by staff.'),
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='linked_item',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optionally link to an inventory item this relates to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockitem'),
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='reason',
            field=models.TextField(help_text='Full explanation / justification'),
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='title',
            field=models.CharField(help_text='Short description of what this is for', max_length=120),
        ),
        migrations.AlterField(
            model_name='meritrequest',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='aUEC amount (MONEY) or merit points (MERIT). 0 = TBD by staff.'),
        ),
        migrations.AlterField(
            model_name='meritrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meritrequest',
            name='linked_item',
            field=models.ForeignKey(blank=True, help_text='Optionally link to an inventory item this relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merit_requests', to='inventory.stockitem'),
        ),
        migrations.AlterField(
            model_name='meritrequest',
            name='reason',
            field=models.TextField(help_text='Full explanation / justification'),
        ),
        migrations.AlterField(
            model_name='meritrequest',
            name='title',
            field=models.CharField(help_text='Short description of what this is for', max_length=120),
        ),
    ]
