# Generated by Django 6.0 on 2026-04-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merits', '0002_alter_historicalmeritrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Auto-generated from submission fields'),
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-generated from submission fields', max_length=120),
        ),
        migrations.AlterField(
            model_name='meritrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Auto-generated from submission fields'),
        ),
        migrations.AlterField(
            model_name='meritrequest',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-generated from submission fields', max_length=120),
        ),
    ]
