# Generated by Django 6.0 on 2026-04-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merits', '0003_alter_historicalmeritrequest_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmeritrequest',
            name='reminder_sent',
        ),
        migrations.RemoveField(
            model_name='meritrequest',
            name='reminder_sent',
        ),
        migrations.AlterField(
            model_name='historicalmeritrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('DENIED', 'Denied')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='meritrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('DENIED', 'Denied')], db_index=True, default='PENDING', max_length=12),
        ),
    ]
