# Generated by Django 6.0 on 2026-04-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplan',
            name='private_thread',
            field=models.BooleanField(default=False, help_text="Create the attendee thread as a private thread (requires server boost level 2). Only RSVP'd members are added; non-RSVP'd members cannot see it."),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='private_thread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='private_thread',
            field=models.BooleanField(default=False, help_text="Create the attendee thread as a private thread (requires server boost level 2). Only RSVP'd members are added; non-RSVP'd members cannot see it."),
        ),
    ]
