# Generated by Django 6.0 on 2026-04-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedevents', '0002_eventplan_private_thread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplan',
            name='announcement_channel_override_id',
            field=models.BigIntegerField(blank=True, help_text='Override the global announcement channel for this event. Leave blank to use the default.', null=True),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='announcement_channel_override_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='announcement_channel_override_id',
            field=models.BigIntegerField(blank=True, help_text='Override the global announcement channel for this event. Leave blank to use the default.', null=True),
        ),
    ]
