# Generated by Django 6.0 on 2026-04-08 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedevents', '0003_eventplan_announcement_channel_override_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Template Category',
                'verbose_name_plural': 'Template Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Group this template under a category (e.g. FPS, Piloting, Support).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='schedevents.templatecategory'),
        ),
    ]
