# Generated by Django 6.0 on 2026-04-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedevents', '0005_sesh_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaleventplan',
            name='allow_maintain_rsvp',
            field=models.BooleanField(default=False, help_text='Carry RSVPs forward when a recurring event repeats.'),
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Per-event embed color override (#RRGGBB). Overrides the indicator color.', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='hide_attendees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='mentions_on_create',
            field=models.JSONField(blank=True, default=list, help_text='Discord role IDs (ints) to ping when event is published.'),
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='mentions_on_start',
            field=models.JSONField(blank=True, default=list, help_text='Discord role IDs (ints) to ping when event goes ACTIVE.'),
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='thread_auto_archive_duration',
            field=models.CharField(choices=[('OneHour', '1 Hour'), ('OneDay', '1 Day'), ('ThreeDays', '3 Days'), ('OneWeek', '1 Week')], default='OneDay', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='thread_join_on_rsvp',
            field=models.BooleanField(default=True, help_text='Auto-add members to attendee thread when they RSVP GOING.'),
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='thread_start_message_type',
            field=models.CharField(choices=[('Thread', 'Post in thread'), ('Channel', 'Post in channel'), ('None', 'No start message')], default='Thread', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaleventplan',
            name='thread_title_template',
            field=models.CharField(blank=True, default='$EventName', help_text='Thread name template. Supports $EventName.', max_length=200),
        ),
        migrations.AddField(
            model_name='historicaleventrsvp',
            name='rsvp_option',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedevents.rsvpoption'),
        ),
        migrations.AlterField(
            model_name='eventreminder',
            name='title_template',
            field=models.CharField(blank=True, help_text='Notification title. Supports $EventName, $DT_TimeRelative. Leave blank for default.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rsvpoption',
            name='capacity_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max RSVPs for this option. Null = unlimited.', null=True),
        ),
    ]
