# Generated by Django 6.0 on 2026-04-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedevents', '0008_eventplan_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaleventplan',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Where the event takes place (shown in Discord scheduled event).', max_length=200),
        ),
    ]
