# Generated by Django 6.0 on 2026-04-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedevents', '0010_merge_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventplan',
            name='require_approval',
        ),
        migrations.RemoveField(
            model_name='historicaleventplan',
            name='require_approval',
        ),
    ]
