# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedevents', '0012_mentions_on_vc_unlock_emoji_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventattendeerole',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='eventindicator',
            options={'default_permissions': (), 'ordering': ['id'], 'permissions': [('can_create_events_with', 'Can create events using this indicator')]},
        ),
        migrations.AlterModelOptions(
            name='eventplan',
            options={'default_permissions': (), 'ordering': ['planned_start_at'], 'permissions': [('can_modify_delete_created', 'Can modify/delete events they created'), ('can_modify_delete_organizer', 'Can modify/delete events they organize'), ('can_publish_events', 'Can publish events'), ('can_force_checkin', 'Can manually check in attendees'), ('can_manage_all_events', 'Can manage any event regardless of ownership')]},
        ),
        migrations.AlterModelOptions(
            name='eventreminder',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='eventreport',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='eventrolerestriction',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='eventrsvp',
            options={'default_permissions': (), 'ordering': ['rsvp_time']},
        ),
        migrations.AlterModelOptions(
            name='eventtemplate',
            options={'default_permissions': (), 'permissions': [('can_create_event_with', 'Can use this template to create events')]},
        ),
        migrations.AlterModelOptions(
            name='rsvpoption',
            options={'default_permissions': (), 'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='templatecategory',
            options={'default_permissions': (), 'ordering': ['sort_order', 'name'], 'verbose_name': 'Template Category', 'verbose_name_plural': 'Template Categories'},
        ),
    ]
