# Generated by Django 6.0 on 2026-04-17 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_uid', models.IntegerField(db_index=True)),
                ('message_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=500)),
                ('thread_root', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('from_address', models.CharField(max_length=500)),
                ('from_name', models.CharField(blank=True, default='', max_length=200)),
                ('to_address', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_outbound', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['received_at'],
                'permissions': [('view_inbox', 'Can view the shared inbox'), ('reply_email', 'Can reply to emails')],
            },
        ),
    ]
