# Generated by Django 6.0 on 2026-04-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'default_permissions': (), 'ordering': ['received_at'], 'permissions': [('view_inbox', 'Can view the shared inbox'), ('reply_email', 'Can reply to emails')]},
        ),
    ]
